### ISSUE TITLE
libinput's debug tools are not stable interfaces

### ISSUE THREAD

**Issue by whot** [iberianpig/fusuma#1]
Not a bug just yet, more a heads-up: the output of the libinput-list-devices and libinput-debug-events tools are not stable interfaces and can change at any time without notice. If you're relying on the exact parsing, then you're running the danger of having your program break randomly.

fwiw, I've also pointed this out here for the libinput-gestures project.
https://github.com/bulletmark/libinput-gestures/issues/18

**Comment by iberianpig** [comment]
Thank you for telling me that.
I will update parser if debug prints are changed.
If secure and stable API are supported by Wayland and major DEs support Gestures with native, such as this project is not needed and I'm happy;).
