### ISSUE TITLE
how can I get the mouse movement value of x and y?

### ISSUE THREAD

**Issue by janlely** [iberianpig/fusuma#102]
In the debug out of fusuma I can see the mouse move infomation:
`move=>{:x=>3.533, :y=>0.0566}`
How can I use the value of x and y just like this:

`command: 'xdotool mouseown 1 mousemove_relative ${x} ${y}'`

**Comment by iberianpig** [comment]
It is the distance you swiped on the touchpad. It supports only swipe and pinch action, but it does not support mouse gesture.
