### ISSUE TITLE
Stops working for 3 minutes

### ISSUE THREAD

**Issue by GiovanniCS** [iberianpig/fusuma#103]
Hi, i'm using fusuma 0.10.2 on Elementary OS 0.4.1 Loki on Acer e3-111.
After the startup of the OS i have defined an automatic custom command (/usr/local/bin/fusuma -d).
If i try to use some three finger gesture, it works for some second after startup but then it stops.
If i wait about 3 minutes, fusuma restart working as expected without doing anything special.
In config.yml i have the following settings https://gist.github.com/GiovanniCS/6e7fa3412028e0c9a07981eb8252be87.
Thanks for your time :)

**Comment by GiovanniCS** [comment]
System settings -> Application -> Startup
Configured as in the attached screenshot.
I already tried with gnome-session-properties and executing fusuma starting from the .profile file.
![fusuma](https://user-images.githubusercontent.com/25981629/47490959-110c5300-d84a-11e8-9f27-74e06eb585bc.png)

**Comment by GiovanniCS** [comment]
I can provide any kind of log files if needed, just let me know !

**Comment by iberianpig** [comment]
Please try following command for logging.

```
fusuma -v > /tmp/fusuma.log
```

Then, you check to find error or warning in logs(`/tmp/fusuma.log/`) in the 3 minutes after restart and some swipes.

**Comment by GiovanniCS** [comment]
I tried rebooting my machine, as usual the gestures stop working after some seconds. When i open a terminal and start logging they start working again even if 3 minutes aren't passed yet. In the log file are present only DEBUG messages. In System Monitor i can see than another fusuma process is started when i try to log (as in the attached screenshot)
![sysmonitor](https://user-images.githubusercontent.com/25981629/47584763-c7139200-d95b-11e8-8bc4-b49d7877b954.png)

**Comment by GiovanniCS** [comment]
If i add that command along with ```fusuma -d``` nothing changes and the log file is not created. But i noted that if i leave only ```fusuma -v > /tmp/fusuma.log``` the gestures work as expected.

**Comment by iberianpig** [comment]
if it works without problem, you only remove `-v > /tmp/fusuma.log`.

**Comment by GiovanniCS** [comment]
> If i add that command along with `fusuma -d` nothing changes and the log file is not created. But i noted that if i leave only `fusuma -v > /tmp/fusuma.log` the gestures work as expected.

Now, after a reboot and without any changes, the problem is still there and log file is still not created. I don't really understand what's going on but i suspect is more an hardware thing than a sw one. This touchpad gave me other problems in the past, so i guess i have to keep it as it is.
Thanks anyway for your help!

**Comment by iberianpig** [comment]
Please try adding fusuma to cerbere on elementary OS instead of gnome-session-properties.
It has auto recovering from application crash.

**Comment by GiovanniCS** [comment]
On [launchpad](https://www.launchpad.net/cerbere) i can read " cerbere monitors a predefined list of processes and relaunches them if they end". This is not the case because, after reboot, if i open System Monitor i can clearly see that fusuma is present in the list of processes and its status is "Running".
Btw, this is not a big problem for me, i can live with it. If you want you can close the issue. Thanks again, despite this inconvenient your work is awesome!

**Comment by iberianpig** [comment]
I am really pleased that you liked the product of my hobbies. 
Please tell me again if you find a problem.
Thank you.
