### ISSUE TITLE
Not recognizing 3 or 4 finger gestures.

### ISSUE THREAD

**Issue by get4prince** [iberianpig/fusuma#106]
really exited to use this feature but not working on my side. 

**but fusuma unable to detect 3 and 4 touch and swipe.**

fusuma -v show that 

![screenshot from 2018-11-20 02-44-50](https://user-images.githubusercontent.com/20876285/48735509-967afb80-ec6e-11e8-9f20-e07e15955c2b.png)
 
libinput-debug-events shows 
![screenshot from 2018-11-20 02-49-09](https://user-images.githubusercontent.com/20876285/48735654-fa9dbf80-ec6e-11e8-91b4-fd2a7683265b.png)

no where is 3, 4 multitouch is detected
i have used my multitouch in window.

thanks for help really exited to use it

**Comment by iberianpig** [comment]
Please paste the output of 3 fingers swipes with running libinput-debug-events.
If you could get a row of beginning with GESTURE_SWIPE_BEGIN, you can use fusuma ;)
