### ISSUE TITLE
Is GNOME a requirement?

### ISSUE THREAD

**Issue by danbohea** [iberianpig/fusuma#107]
I can see from the README that you're using GNOME but is it an actual requirement? Can I run this on KDE Plasma for example? Given that it's Ruby based I'm guessing that's possible?

**Comment by iberianpig** [comment]
Gnome is not requirement.
Because I'm not Gnome user (I'm using Panthenon).
If libinput is installed, you can use fusuma.

**Comment by iberianpig** [comment]
So Fusuma can be executable on KDE Plasma.

**Comment by danbohea** [comment]
Winner. I hoped/assumed as much. Thanks for confirming.
