### ISSUE TITLE
Some gestures are not registered/read correctly

### ISSUE THREAD

**Issue by ihsanauliaa** [iberianpig/fusuma#110]
Hello.
I have used fusuma in Ubuntu 18.04 and it works flawlessly.
Recently, I started using manjaro and some problems appeared.

I successfully installed fusuma, run it in terminal, and it reads the gestures (3 fingers, 4 fingers). But in the fusuma's terminal log, it registered the gesture incorrectly. Three fingers up registered as ctrl+t, three down as ctrl+w, four fingers down as super+s etc.

I've tried to see if the three and four fingers gestures is read correctly by trying to see the visualization with libinput debug-gui, and it reads it perfectly.

I've tried reinstalling ruby, xdotool, and the fusuma itself but the bug still persists.
How can i fix this problem?

Any help is appreciated.

Thanks:)

**Comment by iberianpig** [comment]
It seems that fusuma's default setting is loaded. Please check that your config file is located at ~/.config/fusuma/config.yml

**Comment by ihsanauliaa** [comment]
Yeah it's already there. You're right, i think that fusuma doesn't load my config file at 
![screenshot from 2018-12-27 11-11-06](https://user-images.githubusercontent.com/45911224/50465193-35aab580-09c8-11e9-939d-7d8e5ccd20a1.png)
~/.config/fusuma/config.yml

**Comment by rrhythmsharma** [comment]
@ihsanauliaa, Thanks a lot! for the above information

It worked for me :+1:
