### ISSUE TITLE
Very unreliable on Thinkpad 11e using Elementary OS

### ISSUE THREAD

**Issue by hubrix** [iberianpig/fusuma#12]
Actions are delayed, pinch zoom seems to work relatively well but the 3/4 finger swipes don't work.

 Linux mark-ThinkPad-11e 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by iberianpig** [comment]
@hubrix Has the issue already been solved? I tuned pinch and swipe sensitivities.  Please update Fusuma gem and try it.
And I'll update Fusuma to able to change sensitivity with a config file.

**Comment by iberianpig** [comment]
Please reopen if you have the same issue again.
