### ISSUE TITLE
Fusuma closes with an undefined method `assign_attributes' for nil:NilClass (NoMethodError) error

### ISSUE THREAD

**Issue by sbstratos79** [iberianpig/fusuma#145]
Fusuma closes with an error whenever I try to run it. I have tried libinput debug-events and it detects my trackpad gestures etc.

Here's the terminal output when I start fusuma:

[sbstratos79@Predator ~]$ fusuma
I, [2019-12-19T14:07:51.125712 #15414]  INFO -- : reload config : /home/sbstratos79/.config/fusuma/config.yml
I, [2019-12-19T14:07:51.125810 #15414]  INFO -- : ---------------------------------------------
I, [2019-12-19T14:07:51.125829 #15414]  INFO -- : Fusuma: 1.3.0
I, [2019-12-19T14:07:51.126743 #15414]  INFO -- : libinput: 1.14.3
I, [2019-12-19T14:07:51.127441 #15414]  INFO -- : OS: Linux 4.19.88-1-MANJARO #1 SMP PREEMPT Thu Dec 5 11:04:44 UTC 2019
I, [2019-12-19T14:07:51.127995 #15414]  INFO -- : Distribution: Manjaro Linux \r  (\n) (\l)
I, [2019-12-19T14:07:51.130648 #15414]  INFO -- : Desktop session: gnome
I, [2019-12-19T14:07:51.130670 #15414]  INFO -- : ---------------------------------------------
I, [2019-12-19T14:07:51.130713 #15414]  INFO -- : ---------------------------------------------
I, [2019-12-19T14:07:51.130726 #15414]  INFO -- : Enabled Plugins: 
I, [2019-12-19T14:07:51.130809 #15414]  INFO -- :   Fusuma::Plugin::Buffers::GestureBuffer
I, [2019-12-19T14:07:51.130841 #15414]  INFO -- :   Fusuma::Plugin::Detectors::PinchDetector
I, [2019-12-19T14:07:51.130873 #15414]  INFO -- :   Fusuma::Plugin::Detectors::RotateDetector
I, [2019-12-19T14:07:51.130884 #15414]  INFO -- :   Fusuma::Plugin::Detectors::SwipeDetector
I, [2019-12-19T14:07:51.130895 #15414]  INFO -- :   Fusuma::Plugin::Events::Records::GestureRecord
I, [2019-12-19T14:07:51.130905 #15414]  INFO -- :   Fusuma::Plugin::Events::Records::IndexRecord
I, [2019-12-19T14:07:51.130931 #15414]  INFO -- :   Fusuma::Plugin::Events::Records::TextRecord
I, [2019-12-19T14:07:51.130960 #15414]  INFO -- :   Fusuma::Plugin::Executors::CommandExecutor
I, [2019-12-19T14:07:51.130987 #15414]  INFO -- :   Fusuma::Plugin::Filters::LibinputDeviceFilter
I, [2019-12-19T14:07:51.131020 #15414]  INFO -- :   Fusuma::Plugin::Inputs::LibinputCommandInput
I, [2019-12-19T14:07:51.131047 #15414]  INFO -- :   Fusuma::Plugin::Parsers::LibinputGestureParser
I, [2019-12-19T14:07:51.131078 #15414]  INFO -- : ---------------------------------------------
Traceback (most recent call last):
	26: from /usr/bin/fusuma:23:in `<main>'
	25: from /usr/bin/fusuma:23:in `load'
	24: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/exe/fusuma:41:in `<top (required)>'
	23: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma.rb:18:in `run'
	22: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma.rb:89:in `run'
	21: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma/plugin/inputs/libinput_command_input.rb:21:in `run'
	20: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma/plugin/inputs/libinput_command_input.rb:56:in `debug_events'
	19: from /usr/lib/ruby/2.6.0/open3.rb:101:in `popen3'
	18: from /usr/lib/ruby/2.6.0/open3.rb:219:in `popen_run'
	17: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma/plugin/inputs/libinput_command_input.rb:57:in `block in debug_events'
	16: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma/plugin/inputs/libinput_command_input.rb:57:in `each'
	15: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma/plugin/inputs/libinput_command_input.rb:58:in `block (2 levels) in debug_events'
	14: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma/plugin/inputs/libinput_command_input.rb:22:in `block in run'
	13: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma.rb:90:in `block in run'
	12: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma.rb:100:in `filter'
	11: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma.rb:100:in `any?'
	10: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma.rb:100:in `block in filter'
	 9: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma/plugin/filters/filter.rb:17:in `filter'
	 8: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma/plugin/filters/libinput_device_filter.rb:29:in `keep?'
	 7: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma/plugin/filters/libinput_device_filter.rb:54:in `all'
	 6: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma/device.rb:39:in `available'
	 5: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma/device.rb:33:in `all'
	 4: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma/device.rb:62:in `fetch_devices'
	 3: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma/device.rb:81:in `generate_devices'
	 2: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma/device.rb:81:in `each_with_object'
	 1: from /usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma/device.rb:81:in `each'
/usr/lib/ruby/gems/2.6.0/gems/fusuma-1.3.0/lib/fusuma/device.rb:90:in `block in generate_devices': undefined method `assign_attributes' for nil:NilClass (NoMethodError)

Version Info: 
Fusuma: 1.3.0
libinput: 1.14.3
OS: Linux 4.19.88-1-MANJARO #1 SMP PREEMPT Thu Dec 5 11:04:44 UTC 2019
Distribution: Manjaro Linux \r  (\n) (\l)
Desktop session: gnome

I have used the `gsettings set org.gnome.desktop.peripherals.touchpad send-events enabled` command btw. I know a similar issue has already been posted but none of the solutions mentioned in those issues worked for me. I have not downgraded my libinput because I don't know which version would work.

**Comment by iberianpig** [comment]
I have fixed #149 .
