### ISSUE TITLE
3 finger drag

### ISSUE THREAD

**Issue by foltri** [iberianpig/fusuma#151]
Is there a way to use 3 finger drag with fusuma?

**Comment by iberianpig** [comment]
3 finger drag is not supported now.

BTW, I released [fusuma-plugin-tap](https://github.com/iberianpig/fusuma-plugin-tap)

This gesture detects 1~4 fingers hold(long press).

You can grab the current window and move it. Please see https://github.com/iberianpig/fusuma/issues/38
