### ISSUE TITLE
Capturing Finger Taps on Touchpad

### ISSUE THREAD

**Issue by LakithKarunaratne** [iberianpig/fusuma#152]
Tried to configure Fusuma to translate 3 and 4 finger taps on the Touchpad. 

*For example: 
3 finger tap --> Alt+F7 : move window
4 finger tap --> Alt+F8 : resize window
*
I wasn't able to configure this on the yaml file. Perhaps this could be added as a new feature.
Tested on DELL XPS 9360.

**Comment by iberianpig** [comment]
@LakithKarunaratne I released [fusuma-plugin-tap](https://github.com/iberianpig/fusuma-plugin-tap).
This plugin detects 1~4 fingers tap gestures and hold(long press) gestures.
