### ISSUE TITLE
Problem with fusuma on elementary os

### ISSUE THREAD

**Issue by andreacocci95** [iberianpig/fusuma#153]
HI, I used your script for every distro that I used and it worked well everytime. Now I've installed fusuma on elementary os and I have some problems. When I configure a new confg.yml, when I do the gesture, only sometimes the gesture work well with the new command in the config.yml. Sometimes the gesture do the action defined as default. For example, by default the swipe with 4 finger up do the shortcut "Super+a" and the swipe down do the "Super+s". I should do "Super+s" both for swipe up and down, but despite I configured it in the config.yml, sometimes still performs "Super+a" despite I don't have a gesture with this shortcut in my new conifg.yml. Can you help me?

![Screenshot from 2020-03-01 09-51-55](https://user-images.githubusercontent.com/22175753/75622589-5e1cd980-5ba2-11ea-8c38-e2cd002eb0ef.png)

**Comment by iberianpig** [comment]
Could you check your log of `fusuma` ?

You can find a line begining of `reload config: /path/to/your/config.yml`.

Fusuma use the config reloaded last

```
$ iberianpig@iberianpig-XPS-13-9360:~$ fusuma
I, [2020-03-03T13:59:03.837509 #22169]  INFO -- : reload config : /home/iberianpig/.config/fusuma/config.yml   #← THIS IS YOUR CONFIG FILE
I, [2020-03-03T13:59:03.837561 #22169]  INFO -- : ---------------------------------------------
I, [2020-03-03T13:59:03.837586 #22169]  INFO -- : Fusuma: 1.5.0
I, [2020-03-03T13:59:03.839442 #22169]  INFO -- : libinput: 1.10.4
I, [2020-03-03T13:59:03.840077 #22169]  INFO -- : OS: Linux 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020
I, [2020-03-03T13:59:03.840693 #22169]  INFO -- : Distribution: elementary OS Hera \n \l
I, [2020-03-03T13:59:03.841207 #22169]  INFO -- : Desktop session: pantheon x11
I, [2020-03-03T13:59:03.841226 #22169]  INFO -- : ---------------------------------------------
```
