### ISSUE TITLE
Fusuma not working 

### ISSUE THREAD

**Issue by goutham-nekkalapu** [iberianpig/fusuma#154]
**Describe the bug**
Thank you for building cool feature. Installed the latest version of Fusuma (on ubuntu 18.04 LTS, X11) through the instructions provided but it does not work.Through the issue 106 here : "https://github.com/iberianpig/fusuma/issues/106" found that 'GESTURE_SWIPE_BEGIN' is not there in my  'libinput-debug-events'. 

In the past, I was able to use your 'xswipe' for multi gesture successfully on Ubuntu 16.04 LTS on my laptop. Are there any settings or specific ways to get 'GESTURE_SWIPE_BEGIN'  on Ubuntu 18.04 LTS ?. 

Note: Tested 'xdotool" individually and it works fine for all the 3 figure gestures.

**Comment by iberianpig** [comment]
Have you restarted after adding $USER to input group?

**Comment by goutham-nekkalapu** [comment]
@iberianpig yes, I did

**Comment by iberianpig** [comment]
If you don't get GESTURE_SWIPE_xxxx line from outputs of  libinput debug-events, unfortunately Fusuma cannot recognise gestures.

**Comment by goutham-nekkalapu** [comment]
Thank you for the reply. Do u have any insight on  what  the issue might be for  'GESTURE_SWIPE_xxxx' not being recognized ?. 
Also any pointers as to where I should look to fix this is much appreciated

**Comment by iberianpig** [comment]
It may be the following problem

* Wrong priority setting of driver at  /etc/X11/xorg.conf.d/ or /usr/share/X11/xorg.conf.d/
   * ref: https://wiki.archlinux.org/index.php/Libinput#Via_Xorg_configuration_file

* Libinput doesn't support the device
    * Check if it works with the latest libinput. You need to build and install libinput from source. https://wayland.freedesktop.org/libinput/doc/latest/building.html

**Comment by goutham-nekkalapu** [comment]
@iberianpig Thank you for sharing the links, will use them and try to fix
