### ISSUE TITLE
Best method to launch fusuma at start up

### ISSUE THREAD

**Issue by PrestanceDesign** [iberianpig/fusuma#16]
Hi,

Which is the best method to launch fusuma at start up ?

Ubuntu 16.10
/bin/zsh

Thx you for your work.
Merry christmas !

**Comment by iberianpig** [comment]
If you are using ubuntu, you should try `gnome-session-properties`.
I'm using cerbere for registering as daemon, because my environment is elementary OS.

**Comment by PrestanceDesign** [comment]
Yeah quite simply like xSwipe !
 I do not know where I had the head when I asked the question but I was absolutely looking to do it via upstart or something like that.

Thank you.

**Comment by PrestanceDesign** [comment]
HNY !

So I tried `gnome-session-properties` but without success, maybe because I use `rvm` to manage my ruby environment.

I tried both in command input :
**Absolute path** : /home/user/.rvm/gems/ruby-2.3.3/bin/fusuma &
or directly fusuma.

Syslog line when log in :
`fusuma.desktop[4514]: /usr/bin/env: «ruby_executable_hooks»: Aucun fichier ou dossier de ce type`

**Comment by iberianpig** [comment]
Sorry, I don't know about rvm.
where is your fusuma command?
your error message says 'fusuma correct path is missing'

Please check correct path with below command

```bash
$which fusuma
```

**Comment by PrestanceDesign** [comment]
Thx for your helping.
As I say before, Fusuma path is : `/home/user/.rvm/gems/ruby-2.3.3/bin/fusuma`.
If I launch path in terminal, it works.

**Comment by PrestanceDesign** [comment]
OK
