### ISSUE TITLE
ruby2.7

### ISSUE THREAD

**Issue by minzukas** [iberianpig/fusuma#164]
after terminal: fusuma i get
_bash: /usr/local/bin/fusuma: /usr/bin/ruby2.5: bad interpreter: No such file or directory
currently ruby2.7 installed_

**Comment by iberianpig** [comment]
Are you using rbenv?

Could you confirm that is there following script in your ~/.bashrc ?

```sh
export PATH="$HOME/.rbenv/bin:$PATH" 
eval "$(rbenv init -)
```

**Comment by minzukas** [comment]
I'm currently on Focal Fossa development. Maybe it is too early to report...

./bashrc  is empty.

**Comment by iberianpig** [comment]
Execute the following command to reinstall the software.
It is possible that an OS update may have left behind an old Ruby installation of Fusuma.
```sh
sudo gem uninstall fusuma
sudo gem install fusuma
```

**Comment by minzukas** [comment]
Thank You. Had to

> sudo gem install fusuma

works like a charm
