### ISSUE TITLE
Some gestures are not always recognized

### ISSUE THREAD

**Issue by Trickytram** [iberianpig/fusuma#172]
I am using fusuma only with swipe gestures configured.
I am using three finger swipes and four finger swipes. I've never run into any issues using the four finger swipe (which switches between desktops for me), whereas the three finger swipe (which I use to go back between pages in the browser) frequently does not work. However, when I change the desktops using the four finger swipe there is a high probability that the three finger swipe gesture will work again.

Sadly I dont know if I can provide any helpful logs, so if I can please tell me.

Thanks for your help.

**Comment by iberianpig** [comment]
@Trickytram 
Could you paste outputs of `fusuma --version`?

**Comment by Trickytram** [comment]
Here you go:

I, [2020-05-14T08:49:16.615568 #14931]  INFO -- : ---------------------------------------------
I, [2020-05-14T08:49:16.615606 #14931]  INFO -- : Fusuma: 0.11.1
I, [2020-05-14T08:49:16.618431 #14931]  INFO -- : libinput: 1.10.4
I, [2020-05-14T08:49:16.618984 #14931]  INFO -- : OS: Linux 5.5.15-050515-generic #202004021032 SMP Thu Apr 2 14:37:37 UTC 2020
I, [2020-05-14T08:49:16.619928 #14931]  INFO -- : Distribution: Ubuntu 18.04.4 LTS \n \l
I, [2020-05-14T08:49:16.620394 #14931]  INFO -- : Desktop session: plasma
I, [2020-05-14T08:49:16.620417 #14931]  INFO -- : ---------------------------------------------

**Comment by iberianpig** [comment]
Your Fusuma version is too old!
Please update with `sudo gem update fusuma`

**Comment by Trickytram** [comment]
Alright I will do that.
Thank you. I will close this issue.
If the problem reappears I will open another issue.
