### ISSUE TITLE
config.yml file is not updating

### ISSUE THREAD

**Issue by Trevinno** [iberianpig/fusuma#183]
I was able to write into the config.yml file the sample configurations you listed which are:
wipe:
  3: 
    left: 
      command: 'xdotool key alt+Right'
    right: 
      command: 'xdotool key alt+Left'
    up: 
      command: 'xdotool key super'
    down: 
      command: 'xdotool key super'

threshold:
  swipe: 0.4
 
interval:
  swipe: 0.8
 

It worked but now I want to inverse the directions so when you swipe left alt+left is activated and such. I changed the config file to the following:

  3: 
    left: 
      command: 'xdotool key alt+Left'
    right: 
      command: 'xdotool key alt+Right'
    up: 
      command: 'xdotool key super'
    down: 
      command: 'xdotool key super'

I saved this change and the config.yml file did change but the swiping directions remained the same  .

**Comment by iberianpig** [comment]
Could you paste output of `fusuma -v`
and complete configuration file, not just a part of it.

And please quote codes with triple backquote ```
