### ISSUE TITLE
Disable Ubuntu Unity Multitouch Gestures

### ISSUE THREAD

**Issue by Pazuu** [iberianpig/fusuma#19]
First of all, thank you so much for your work!! 
It seems to work great, and i have been looking for such a tool for so long! Thanks!

I was able to disable the 3 Finger Tab multitouch standard gestures of Unity with this commands:
synclient ClickFinger3=2
synclient TapButton3=2 

But i am struggling now to find an easy way to disable the 4 Finger "show Dash" multitouch gesture... 
Any Ideas? (Sorry i know, this is not an issue with this program!)

Have a wonderful day everyone!

**Comment by iberianpig** [comment]
Sorry, I have no idea.

**Comment by Pazuu** [comment]
I keep on looking for an easy solution :)

**Comment by iberianpig** [comment]
Sorry that I couldn't be of any help to you about the specific issue of Ubuntu Unity.
