### ISSUE TITLE
Opening application with fusuma

### ISSUE THREAD

**Issue by Pinche-Dev** [iberianpig/fusuma#218]
Can't fusuma be configured such that it opens application like calculator 
using it on Hold can become handy

**Comment by iberianpig** [comment]
Hi @Pinche-Dev 

> Can't fusuma be configured such that it opens application like calculator
> using it on Hold can become handy

Which one did you mean?

1. binding `hold gesture` to open calculator
1. Configure settings for specific applications (wm_class/window name)

**Comment by iberianpig** [comment]
1 → Try hold gesture in https://github.com/iberianpig/fusuma-plugin-tap 

2 → Please wait to release https://github.com/iberianpig/fusuma-plugin-application_matcher (work in progress)

**Comment by iberianpig** [comment]
I released  [fusuma-plugin-appmatcher](https://github.com/iberianpig/fusuma-plugin-appmatcher) depend on fusuma v2(need to update gem). Please try it.
