### ISSUE TITLE
Fusuma doing nothing on ubuntu 16.04

### ISSUE THREAD

**Issue by prasantadh** [iberianpig/fusuma#22]
I am using ubuntu 16.04 on Fusuma isn't doing anything at the moment at all.

The output of `fusuma -v` is as follows:
`D, [2017-01-11T06:22:45.416046 #31763] DEBUG -- : Device:           Power Button

D, [2017-01-11T06:22:45.416146 #31763] DEBUG -- : Kernel:           /dev/input/event3

D, [2017-01-11T06:22:45.416224 #31763] DEBUG -- : Group:            1

D, [2017-01-11T06:22:45.416252 #31763] DEBUG -- : Seat:             seat0, default

D, [2017-01-11T06:22:45.416269 #31763] DEBUG -- : Capabilities:     keyboard 

D, [2017-01-11T06:22:45.416283 #31763] DEBUG -- : Tap-to-click:     n/a

D, [2017-01-11T06:22:45.416303 #31763] DEBUG -- : Tap-and-drag:     n/a

D, [2017-01-11T06:22:45.416317 #31763] DEBUG -- : Tap drag lock:    n/a

D, [2017-01-11T06:22:45.416329 #31763] DEBUG -- : Left-handed:      n/a

D, [2017-01-11T06:22:45.416342 #31763] DEBUG -- : Nat.scrolling:    n/a

D, [2017-01-11T06:22:45.416354 #31763] DEBUG -- : Middle emulation: n/a

D, [2017-01-11T06:22:45.416366 #31763] DEBUG -- : Calibration:      n/a

D, [2017-01-11T06:22:45.416379 #31763] DEBUG -- : Scroll methods:   none

D, [2017-01-11T06:22:45.416391 #31763] DEBUG -- : Click methods:    none

D, [2017-01-11T06:22:45.416403 #31763] DEBUG -- : Disable-w-typing: n/a

D, [2017-01-11T06:22:45.416415 #31763] DEBUG -- : Accel profiles:   n/a

D, [2017-01-11T06:22:45.416427 #31763] DEBUG -- : 

D, [2017-01-11T06:22:45.416440 #31763] DEBUG -- : Device:           Video Bus

D, [2017-01-11T06:22:45.416452 #31763] DEBUG -- : Kernel:           /dev/input/event5

D, [2017-01-11T06:22:45.416468 #31763] DEBUG -- : Group:            2

D, [2017-01-11T06:22:45.416481 #31763] DEBUG -- : Seat:             seat0, default

D, [2017-01-11T06:22:45.416494 #31763] DEBUG -- : Capabilities:     keyboard 

D, [2017-01-11T06:22:45.416506 #31763] DEBUG -- : Tap-to-click:     n/a

D, [2017-01-11T06:22:45.416520 #31763] DEBUG -- : Tap-and-drag:     n/a

D, [2017-01-11T06:22:45.416535 #31763] DEBUG -- : Tap drag lock:    n/a

D, [2017-01-11T06:22:45.416547 #31763] DEBUG -- : Left-handed:      n/a

D, [2017-01-11T06:22:45.416560 #31763] DEBUG -- : Nat.scrolling:    n/a

D, [2017-01-11T06:22:45.416572 #31763] DEBUG -- : Middle emulation: n/a

D, [2017-01-11T06:22:45.416584 #31763] DEBUG -- : Calibration:      n/a

D, [2017-01-11T06:22:45.416596 #31763] DEBUG -- : Scroll methods:   none

D, [2017-01-11T06:22:45.416608 #31763] DEBUG -- : Click methods:    none

D, [2017-01-11T06:22:45.416621 #31763] DEBUG -- : Disable-w-typing: n/a

D, [2017-01-11T06:22:45.416633 #31763] DEBUG -- : Accel profiles:   n/a

D, [2017-01-11T06:22:45.416645 #31763] DEBUG -- : 

D, [2017-01-11T06:22:45.416657 #31763] DEBUG -- : Device:           Power Button

D, [2017-01-11T06:22:45.416797 #31763] DEBUG -- : Kernel:           /dev/input/event1

D, [2017-01-11T06:22:45.416812 #31763] DEBUG -- : Group:            3

D, [2017-01-11T06:22:45.416826 #31763] DEBUG -- : Seat:             seat0, default

D, [2017-01-11T06:22:45.416840 #31763] DEBUG -- : Capabilities:     keyboard 

D, [2017-01-11T06:22:45.416853 #31763] DEBUG -- : Tap-to-click:     n/a

D, [2017-01-11T06:22:45.416866 #31763] DEBUG -- : Tap-and-drag:     n/a

D, [2017-01-11T06:22:45.416879 #31763] DEBUG -- : Tap drag lock:    n/a

D, [2017-01-11T06:22:45.416891 #31763] DEBUG -- : Left-handed:      n/a

D, [2017-01-11T06:22:45.416903 #31763] DEBUG -- : Nat.scrolling:    n/a

D, [2017-01-11T06:22:45.416916 #31763] DEBUG -- : Middle emulation: n/a

D, [2017-01-11T06:22:45.416928 #31763] DEBUG -- : Calibration:      n/a

D, [2017-01-11T06:22:45.416940 #31763] DEBUG -- : Scroll methods:   none

D, [2017-01-11T06:22:45.416952 #31763] DEBUG -- : Click methods:    none

D, [2017-01-11T06:22:45.416964 #31763] DEBUG -- : Disable-w-typing: n/a

D, [2017-01-11T06:22:45.416976 #31763] DEBUG -- : Accel profiles:   n/a

D, [2017-01-11T06:22:45.416988 #31763] DEBUG -- : 

D, [2017-01-11T06:22:45.417001 #31763] DEBUG -- : Device:           Sleep Button

D, [2017-01-11T06:22:45.417015 #31763] DEBUG -- : Kernel:           /dev/input/event2

D, [2017-01-11T06:22:45.417029 #31763] DEBUG -- : Group:            4

D, [2017-01-11T06:22:45.417041 #31763] DEBUG -- : Seat:             seat0, default

D, [2017-01-11T06:22:45.417054 #31763] DEBUG -- : Capabilities:     keyboard 

D, [2017-01-11T06:22:45.417066 #31763] DEBUG -- : Tap-to-click:     n/a

D, [2017-01-11T06:22:45.417079 #31763] DEBUG -- : Tap-and-drag:     n/a

D, [2017-01-11T06:22:45.417091 #31763] DEBUG -- : Tap drag lock:    n/a

D, [2017-01-11T06:22:45.417103 #31763] DEBUG -- : Left-handed:      n/a

D, [2017-01-11T06:22:45.417115 #31763] DEBUG -- : Nat.scrolling:    n/a

D, [2017-01-11T06:22:45.417127 #31763] DEBUG -- : Middle emulation: n/a

D, [2017-01-11T06:22:45.417139 #31763] DEBUG -- : Calibration:      n/a

D, [2017-01-11T06:22:45.417151 #31763] DEBUG -- : Scroll methods:   none

D, [2017-01-11T06:22:45.417163 #31763] DEBUG -- : Click methods:    none

D, [2017-01-11T06:22:45.417177 #31763] DEBUG -- : Disable-w-typing: n/a

D, [2017-01-11T06:22:45.417189 #31763] DEBUG -- : Accel profiles:   n/a

D, [2017-01-11T06:22:45.417201 #31763] DEBUG -- : 

D, [2017-01-11T06:22:45.417213 #31763] DEBUG -- : Device:           Laptop_Integrated_Webcam_HD

D, [2017-01-11T06:22:45.417226 #31763] DEBUG -- : Kernel:           /dev/input/event13

D, [2017-01-11T06:22:45.417240 #31763] DEBUG -- : Group:            5

D, [2017-01-11T06:22:45.417252 #31763] DEBUG -- : Seat:             seat0, default

D, [2017-01-11T06:22:45.417426 #31763] DEBUG -- : Capabilities:     keyboard 

D, [2017-01-11T06:22:45.417440 #31763] DEBUG -- : Tap-to-click:     n/a

D, [2017-01-11T06:22:45.417453 #31763] DEBUG -- : Tap-and-drag:     n/a

D, [2017-01-11T06:22:45.417466 #31763] DEBUG -- : Tap drag lock:    n/a

D, [2017-01-11T06:22:45.417486 #31763] DEBUG -- : Left-handed:      n/a

D, [2017-01-11T06:22:45.417497 #31763] DEBUG -- : Nat.scrolling:    n/a

D, [2017-01-11T06:22:45.417510 #31763] DEBUG -- : Middle emulation: n/a

D, [2017-01-11T06:22:45.417522 #31763] DEBUG -- : Calibration:      n/a

D, [2017-01-11T06:22:45.417533 #31763] DEBUG -- : Scroll methods:   none

D, [2017-01-11T06:22:45.417544 #31763] DEBUG -- : Click methods:    none

D, [2017-01-11T06:22:45.417555 #31763] DEBUG -- : Disable-w-typing: n/a

D, [2017-01-11T06:22:45.417566 #31763] DEBUG -- : Accel profiles:   n/a

D, [2017-01-11T06:22:45.417577 #31763] DEBUG -- : 

D, [2017-01-11T06:22:45.417589 #31763] DEBUG -- : Device:           AT Translated Set 2 keyboard

D, [2017-01-11T06:22:45.417600 #31763] DEBUG -- : Kernel:           /dev/input/event4

D, [2017-01-11T06:22:45.417613 #31763] DEBUG -- : Group:            6

D, [2017-01-11T06:22:45.417625 #31763] DEBUG -- : Seat:             seat0, default

D, [2017-01-11T06:22:45.417636 #31763] DEBUG -- : Capabilities:     keyboard 

D, [2017-01-11T06:22:45.417647 #31763] DEBUG -- : Tap-to-click:     n/a

D, [2017-01-11T06:22:45.417661 #31763] DEBUG -- : Tap-and-drag:     n/a

D, [2017-01-11T06:22:45.417673 #31763] DEBUG -- : Tap drag lock:    n/a

D, [2017-01-11T06:22:45.417684 #31763] DEBUG -- : Left-handed:      n/a

D, [2017-01-11T06:22:45.417695 #31763] DEBUG -- : Nat.scrolling:    n/a

D, [2017-01-11T06:22:45.417707 #31763] DEBUG -- : Middle emulation: n/a

D, [2017-01-11T06:22:45.417718 #31763] DEBUG -- : Calibration:      n/a

D, [2017-01-11T06:22:45.417729 #31763] DEBUG -- : Scroll methods:   none

D, [2017-01-11T06:22:45.417740 #31763] DEBUG -- : Click methods:    none

D, [2017-01-11T06:22:45.417751 #31763] DEBUG -- : Disable-w-typing: n/a

D, [2017-01-11T06:22:45.417762 #31763] DEBUG -- : Accel profiles:   n/a

D, [2017-01-11T06:22:45.417773 #31763] DEBUG -- : 

D, [2017-01-11T06:22:45.417784 #31763] DEBUG -- : Device:           AlpsPS/2 ALPS GlidePoint

D, [2017-01-11T06:22:45.417796 #31763] DEBUG -- : Kernel:           /dev/input/event6

D, [2017-01-11T06:22:45.417808 #31763] DEBUG -- : Group:            7

D, [2017-01-11T06:22:45.417960 #31763] DEBUG -- : Seat:             seat0, default

D, [2017-01-11T06:22:45.417973 #31763] DEBUG -- : Size:             95.24x43.75mm

D, [2017-01-11T06:22:45.417985 #31763] DEBUG -- : Capabilities:     pointer 

D, [2017-01-11T06:22:45.417996 #31763] DEBUG -- : Tap-to-click:     disabled

D, [2017-01-11T06:22:45.418026 #31763] DEBUG -- : {:libinput_command=>"stdbuf -oL -- libinput-debug-events --device       /dev/input/event6 --enable-dwt"}`

Nothing else changes when I make any gestures. Looking around the issues I saw the debug console printed out the gestures made. Not for me so far.

Here's the output of `libinput-list-devices`:

`Device:           Power Button
Kernel:           /dev/input/event3
Group:            1
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a

Device:           Video Bus
Kernel:           /dev/input/event5
Group:            2
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a

Device:           Power Button
Kernel:           /dev/input/event1
Group:            3
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a

Device:           Sleep Button
Kernel:           /dev/input/event2
Group:            4
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a

Device:           Laptop_Integrated_Webcam_HD
Kernel:           /dev/input/event13
Group:            5
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a

Device:           AT Translated Set 2 keyboard
Kernel:           /dev/input/event4
Group:            6
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a

Device:           AlpsPS/2 ALPS GlidePoint
Kernel:           /dev/input/event6
Group:            7
Seat:             seat0, default
Size:             95.24x43.75mm
Capabilities:     pointer 
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    none
Disable-w-typing: enabled
Accel profiles:   none

Device:           Dell WMI hotkeys
Kernel:           /dev/input/event14
Group:            8
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a`

And `ps aux | grep libinput` I am not sure if this one helps but I saw it was a part of debug process in one of the issues.
`p  31767  0.1  0.0  34656  1736 pts/6    S+   06:22   0:00 libinput-debug-events --device /dev/input/event6 --enable-dwt
p  32194  0.0  0.0  14224  1092 pts/2    S+   06:33   0:00 grep --color=auto libinput`

Thank you!

**Comment by iberianpig** [comment]
please confirm log with below command

```
$ libinput-debug-events --device /dev/input/event6
```

Then please swipe on your touchpad.
Could you find the text like below in the output?

```
event6 	GESTURE_SWIPE_UPDATE +12.10s	4  7.25/ 0.00 (12.53/ 0.00 unaccelerated)
```

**Comment by prasantadh** [comment]
The command `libinput-debug-events --device /dev/input/event6` gives me first
`event6 	DEVICE_ADDED     AlpsPS/2 ALPS GlidePoint          seat0 default group1 cap:p	size 95.24/43.75mm tap(dl off) left scroll-nat scroll-2fg-edge dwt-on`

 and then on swipe something similar to:
`event6 	POINTER_MOTION    +1.47s	 -0.06/  0.00`
or 
`event6 	POINTER_AXIS      +6.45s	vert 2.71* horiz 0.00`
or
`libinput error: libinput bug: Event for missing capability CAP_GESTURE on device "AlpsPS/2 ALPS GlidePoint"`

The first one was for single finger gesture, the second one is for two finger gesture and the third one is for a three or four finger gesture. I am essentially trying to emulate some mac-like behavior with ubuntu. I am using unity desktop environment and have confirmed that thee trackpad supports up to 4 finger gestures with `geisview`.

**Comment by iberianpig** [comment]
It seems not to able to catch 3/4  fingers swipe event with libinput driver.
This is libinput driver's issue.
So that, you can't use fusuma even if libinput driver supports 1/2 finger swipe with your touchpad.
