### ISSUE TITLE
Allow disabling of repetition

### ISSUE THREAD

**Issue by jbytes1027** [iberianpig/fusuma#221]
**Is your feature request related to a problem? Please describe.**
actions are done multiple times per gesture and increasing the interval settings to an absurdly high number stops from gestures working at all.

**Describe the solution you'd like**
Create a way to stop any gestures or at least the used gesture from repeating after the gesture is performed once.

**Comment by iberianpig** [comment]
If the interval is a large value, it should take time after it is executed once.
Are you sure that the action will never be triggered?
