### ISSUE TITLE
Uninstall Fusuma

### ISSUE THREAD

**Issue by huyhoang8398** [iberianpig/fusuma#228]
**Describe the bug**
Cannot uninstall fusuma

**To Reproduce**
1. sudo gem install fusuma
2. sudo gem uninstall fusuma
3. Removing fusuma
ERROR:  While executing gem ... (NameError)
    uninitialized constant Gem::RDoc

**Expected behavior**

Uninstall fusuma successful

**Versions**
You can get this information from copy and paste the output of `fusuma --version` from the command line. Also, please include the OS and what version of the OS you're running.
OS: Archlinux

**Comment by catalyst17** [comment]
Yo, had the same problem. Try `sudo gem install rdoc` first :)

**Comment by iberianpig** [comment]
Is this an Archlinux related issue?

**Comment by catalyst17** [comment]
> Is this an Archlinux related issue?

Seems to be it, yes.By the way, I started to have another issue now, with fusuma stopping working after a while, no matter,

**Comment by iberianpig** [comment]
> Seems to be it, yes.

Thank you very much. I don't know the details, but it may be that the Ruby installed from pacman does not have rdoc.

---

>By the way, I started to have another issue now, with fusuma stopping working after a while, no matter, has it been started on autostart or by the fusuma -d command. Do I need to create the separate issue? :(

We apologize for the inconvenience, but please submit another issue.

As a hint to find out why a running script stops, it would be helpful to have the logs.
Please try `$ fusuma > logs.txt ` to see if it reproduces.

**Comment by huyhoang8398** [comment]
> By the way, I started to have another issue now, with fusuma stopping working after a while, no matter, has it been started on autostart or by the `fusuma -d` command. Do I need to create the separate issue? :(

I think i will close this issue, can you open a new case for your problem @catalyst17.
Thanks @catalyst17 @iberianpig for your answers
