### ISSUE TITLE
Not Working in ElementaryOS Loki

### ISSUE THREAD

**Issue by kenedyroger** [iberianpig/fusuma#23]
Hello!
Can It works with ElementaryOS Loki and touchpad "ETPS/2 Elantech Touchpad"?

I follow README and not get errors but any gestures works.
PS: On Windows7 my touchpad works multigestures.

*Sorry if I wrote wrong text. I'm not English native.

**Comment by iberianpig** [comment]
please confirm the log with below command

```
$ libinput-debug-events
```

Then please swipe on your touchpad.
Could you find the text like below in the output?

```
event6 	GESTURE_SWIPE_UPDATE +12.10s	4  7.25/ 0.00 (12.53/ 0.00 unaccelerated)
```

**Comment by kenedyroger** [comment]
When I use touch the message log shows:

libinput error: libinput bug: Event for missing capability CAP_GESTURE on
device "ETPS/2 Elantech Touchpad"



2017-01-20 2:31 GMT-02:00 Kohei Yamada <notifications@github.com>:

**Comment by iberianpig** [comment]
This is the issue of libinput driver, therefore Fusuma can't recognize your gesture.

**Comment by get4prince** [comment]
hey there my  2 pinch is working fine but the problem is with 3 and 4 finger . 
in 3 and 4 finger in get same event6   POINTER_AXIS
