### ISSUE TITLE
Is any supported hardware list available?

### ISSUE THREAD

**Issue by gvgit** [iberianpig/fusuma#25]
Is there a hardware list which shows how well a touchpad works with fusuma? I have desktop touchpads in mind but a laptop touchpad list would also be fine.

**Comment by iberianpig** [comment]
@gvgit No, I don't have the list.
It depends on whether libinput support the device.
BTW, I'm using Dell XPS 13. The touchpad works fine.
And Logitech t650 wireless touchpad in my office also works fine.

**Comment by gvgit** [comment]
@iberianpig  I understand. Thanks for info.
