### ISSUE TITLE
mentioning of AUR-Builds in the Archsection?

### ISSUE THREAD

**Issue by Shadowphoenix** [iberianpig/fusuma#276]
someone has built installscripts for the AUR, where you can pull all dependencies and all plugins as opt-depends - maybe mention them ^^

one would still need to add onesself to inputgroup but your command will do that

Link: https://aur.archlinux.org/packages/ruby-fusuma

**Comment by iberianpig** [comment]
I think the install scripts are useful, but some issues make it difficult to let users know what is happening behind the scenes. In particular, if you add $USER to the input group, the executing user needs to know that /dev/inputs/ will be readable.

**Comment by Shadowphoenix** [comment]
Maybe im just blissfully ignorant or blind but at least to me it seems this also does not get mentioned anywhere in your Readme/Documentations here on github.

**Comment by Shadowphoenix** [comment]
yeap, checked again - /dev/input being readable when you are part of Group input is missing in your documentation here (so you probably want to edit your readme accordingly). will make a merge request about that now. merge at your own discretion.

**Comment by Shadowphoenix** [comment]
https://github.com/iberianpig/fusuma/pull/289
