### ISSUE TITLE
Fusuma setup instructions for Fedora 

### ISSUE THREAD

**Issue by thaneesh-babu** [iberianpig/fusuma#277]
**Is your feature request related to a problem? Please describe.**
No instructions on setting up fusuma on Fedora.

**Describe the solution you'd like**
Update the README to include the following instructions:

#### 1. Install libinput-tools

You need `libinput` release 1.0 or later.

```bash
sudo dnf install libinput
```

#### 2. Install Ruby

Fusuma runs in Ruby, so you must install it first.

```bash
sudo dnf install ruby
```

#### 3. Install Fusuma

```bash
sudo gem install fusuma
```

#### 4. Install xdotool (optional)

For sending shortcuts:

```bash
sudo dnf install xdotool
```

**Comment by iberianpig** [comment]
Thanks for your suggestion.
Cloud you make a pull request for updating README.md?

**Comment by TomSchammo** [comment]
I think there is actually a mistake here. Section 3 should be `sudo gem install fusuma`. Fusuma is not in the repos (at least not on Fedora 34).

**Comment by thaneesh-babu** [comment]
> I think there is actually a mistake here. Section 3 should be `sudo gem install fusuma`. Fusuma is not in the repos (at least not on Fedora 34).

You're right, updating the issue now.
