### ISSUE TITLE
fusuma not working

### ISSUE THREAD

**Issue by crpig** [iberianpig/fusuma#28]
Here is the log output, can you help figure out what's wrong with the environment?

D, [2017-01-28T11:00:42.191649 #4407] DEBUG -- : Device:           Power Button

D, [2017-01-28T11:00:42.192361 #4407] DEBUG -- : Kernel:           /dev/input/event2

D, [2017-01-28T11:00:42.192615 #4407] DEBUG -- : Group:            1

D, [2017-01-28T11:00:42.192729 #4407] DEBUG -- : Seat:             seat0, default

D, [2017-01-28T11:00:42.192836 #4407] DEBUG -- : Capabilities:     keyboard 

D, [2017-01-28T11:00:42.192922 #4407] DEBUG -- : Tap-to-click:     n/a

D, [2017-01-28T11:00:42.193029 #4407] DEBUG -- : Tap-and-drag:     n/a

D, [2017-01-28T11:00:42.193111 #4407] DEBUG -- : Tap drag lock:    n/a

D, [2017-01-28T11:00:42.193193 #4407] DEBUG -- : Left-handed:      n/a

D, [2017-01-28T11:00:42.193281 #4407] DEBUG -- : Nat.scrolling:    n/a

D, [2017-01-28T11:00:42.193366 #4407] DEBUG -- : Middle emulation: n/a

D, [2017-01-28T11:00:42.193445 #4407] DEBUG -- : Calibration:      n/a

D, [2017-01-28T11:00:42.193524 #4407] DEBUG -- : Scroll methods:   none

D, [2017-01-28T11:00:42.193602 #4407] DEBUG -- : Click methods:    none

D, [2017-01-28T11:00:42.193681 #4407] DEBUG -- : Disable-w-typing: n/a

D, [2017-01-28T11:00:42.193759 #4407] DEBUG -- : Accel profiles:   n/a

D, [2017-01-28T11:00:42.193836 #4407] DEBUG -- : 

D, [2017-01-28T11:00:42.193917 #4407] DEBUG -- : Device:           Video Bus

D, [2017-01-28T11:00:42.194005 #4407] DEBUG -- : Kernel:           /dev/input/event4

D, [2017-01-28T11:00:42.194099 #4407] DEBUG -- : Group:            2

D, [2017-01-28T11:00:42.194181 #4407] DEBUG -- : Seat:             seat0, default

D, [2017-01-28T11:00:42.194263 #4407] DEBUG -- : Capabilities:     keyboard 

D, [2017-01-28T11:00:42.194343 #4407] DEBUG -- : Tap-to-click:     n/a

D, [2017-01-28T11:00:42.194428 #4407] DEBUG -- : Tap-and-drag:     n/a

D, [2017-01-28T11:00:42.194507 #4407] DEBUG -- : Tap drag lock:    n/a

D, [2017-01-28T11:00:42.194584 #4407] DEBUG -- : Left-handed:      n/a

D, [2017-01-28T11:00:42.195145 #4407] DEBUG -- : Nat.scrolling:    n/a

D, [2017-01-28T11:00:42.195243 #4407] DEBUG -- : Middle emulation: n/a

D, [2017-01-28T11:00:42.195325 #4407] DEBUG -- : Calibration:      n/a

D, [2017-01-28T11:00:42.195402 #4407] DEBUG -- : Scroll methods:   none

D, [2017-01-28T11:00:42.195489 #4407] DEBUG -- : Click methods:    none

D, [2017-01-28T11:00:42.195569 #4407] DEBUG -- : Disable-w-typing: n/a

D, [2017-01-28T11:00:42.195648 #4407] DEBUG -- : Accel profiles:   n/a

D, [2017-01-28T11:00:42.195726 #4407] DEBUG -- : 

D, [2017-01-28T11:00:42.195806 #4407] DEBUG -- : Device:           Sleep Button

D, [2017-01-28T11:00:42.195886 #4407] DEBUG -- : Kernel:           /dev/input/event0

D, [2017-01-28T11:00:42.195977 #4407] DEBUG -- : Group:            3

D, [2017-01-28T11:00:42.196058 #4407] DEBUG -- : Seat:             seat0, default

D, [2017-01-28T11:00:42.196140 #4407] DEBUG -- : Capabilities:     keyboard 

D, [2017-01-28T11:00:42.196220 #4407] DEBUG -- : Tap-to-click:     n/a

D, [2017-01-28T11:00:42.196312 #4407] DEBUG -- : Tap-and-drag:     n/a

D, [2017-01-28T11:00:42.196391 #4407] DEBUG -- : Tap drag lock:    n/a

D, [2017-01-28T11:00:42.196468 #4407] DEBUG -- : Left-handed:      n/a

D, [2017-01-28T11:00:42.196554 #4407] DEBUG -- : Nat.scrolling:    n/a

D, [2017-01-28T11:00:42.196654 #4407] DEBUG -- : Middle emulation: n/a

D, [2017-01-28T11:00:42.196763 #4407] DEBUG -- : Calibration:      n/a

D, [2017-01-28T11:00:42.196871 #4407] DEBUG -- : Scroll methods:   none

D, [2017-01-28T11:00:42.196979 #4407] DEBUG -- : Click methods:    none

D, [2017-01-28T11:00:42.197088 #4407] DEBUG -- : Disable-w-typing: n/a

D, [2017-01-28T11:00:42.197202 #4407] DEBUG -- : Accel profiles:   n/a

D, [2017-01-28T11:00:42.197311 #4407] DEBUG -- : 

D, [2017-01-28T11:00:42.197422 #4407] DEBUG -- : Device:           AT Translated Set 2 keyboard

D, [2017-01-28T11:00:42.197532 #4407] DEBUG -- : Kernel:           /dev/input/event3

D, [2017-01-28T11:00:42.197664 #4407] DEBUG -- : Group:            4

D, [2017-01-28T11:00:42.197779 #4407] DEBUG -- : Seat:             seat0, default

D, [2017-01-28T11:00:42.197887 #4407] DEBUG -- : Capabilities:     keyboard 

D, [2017-01-28T11:00:42.197975 #4407] DEBUG -- : Tap-to-click:     n/a

D, [2017-01-28T11:00:42.198051 #4407] DEBUG -- : Tap-and-drag:     n/a

D, [2017-01-28T11:00:42.198115 #4407] DEBUG -- : Tap drag lock:    n/a

D, [2017-01-28T11:00:42.198179 #4407] DEBUG -- : Left-handed:      n/a

D, [2017-01-28T11:00:42.198240 #4407] DEBUG -- : Nat.scrolling:    n/a

D, [2017-01-28T11:00:42.198315 #4407] DEBUG -- : Middle emulation: n/a

D, [2017-01-28T11:00:42.198379 #4407] DEBUG -- : Calibration:      n/a

D, [2017-01-28T11:00:42.198444 #4407] DEBUG -- : Scroll methods:   none

D, [2017-01-28T11:00:42.198509 #4407] DEBUG -- : Click methods:    none

D, [2017-01-28T11:00:42.198569 #4407] DEBUG -- : Disable-w-typing: n/a

D, [2017-01-28T11:00:42.198629 #4407] DEBUG -- : Accel profiles:   n/a

D, [2017-01-28T11:00:42.198688 #4407] DEBUG -- : 

D, [2017-01-28T11:00:42.198750 #4407] DEBUG -- : Device:           SynPS/2 Synaptics TouchPad

D, [2017-01-28T11:00:42.198822 #4407] DEBUG -- : Kernel:           /dev/input/event5

D, [2017-01-28T11:00:42.199435 #4407] DEBUG -- : Group:            5

D, [2017-01-28T11:00:42.199516 #4407] DEBUG -- : Seat:             seat0, default

D, [2017-01-28T11:00:42.199586 #4407] DEBUG -- : Size:             92.73x39.92mm

D, [2017-01-28T11:00:42.199654 #4407] DEBUG -- : Capabilities:     pointer 

D, [2017-01-28T11:00:42.199725 #4407] DEBUG -- : Tap-to-click:     disabled

D, [2017-01-28T11:00:42.199803 #4407] DEBUG -- : Tap-and-drag:     enabled

D, [2017-01-28T11:00:42.199875 #4407] DEBUG -- : Tap drag lock:    disabled

D, [2017-01-28T11:00:42.199944 #4407] DEBUG -- : Left-handed:      disabled

D, [2017-01-28T11:00:42.200012 #4407] DEBUG -- : Nat.scrolling:    disabled

D, [2017-01-28T11:00:42.200080 #4407] DEBUG -- : Middle emulation: n/a

D, [2017-01-28T11:00:42.200147 #4407] DEBUG -- : Calibration:      n/a

D, [2017-01-28T11:00:42.200209 #4407] DEBUG -- : Scroll methods:   *two-finger edge 

D, [2017-01-28T11:00:42.200292 #4407] DEBUG -- : Click methods:    none

D, [2017-01-28T11:00:42.200363 #4407] DEBUG -- : Disable-w-typing: enabled

D, [2017-01-28T11:00:42.200431 #4407] DEBUG -- : Accel profiles:   none

D, [2017-01-28T11:00:42.200494 #4407] DEBUG -- : 

D, [2017-01-28T11:00:42.200563 #4407] DEBUG -- : Device:           HP Wireless hotkeys

D, [2017-01-28T11:00:42.200633 #4407] DEBUG -- : Kernel:           /dev/input/event6

D, [2017-01-28T11:00:42.200711 #4407] DEBUG -- : Group:            6

D, [2017-01-28T11:00:42.200782 #4407] DEBUG -- : Seat:             seat0, default

D, [2017-01-28T11:00:42.200850 #4407] DEBUG -- : Capabilities:     keyboard 

D, [2017-01-28T11:00:42.200916 #4407] DEBUG -- : Tap-to-click:     n/a

D, [2017-01-28T11:00:42.200993 #4407] DEBUG -- : Tap-and-drag:     n/a

D, [2017-01-28T11:00:42.201061 #4407] DEBUG -- : Tap drag lock:    n/a

D, [2017-01-28T11:00:42.201130 #4407] DEBUG -- : Left-handed:      n/a

D, [2017-01-28T11:00:42.201196 #4407] DEBUG -- : Nat.scrolling:    n/a

D, [2017-01-28T11:00:42.201269 #4407] DEBUG -- : Middle emulation: n/a

D, [2017-01-28T11:00:42.201337 #4407] DEBUG -- : Calibration:      n/a

D, [2017-01-28T11:00:42.201405 #4407] DEBUG -- : Scroll methods:   none

D, [2017-01-28T11:00:42.201471 #4407] DEBUG -- : Click methods:    none

D, [2017-01-28T11:00:42.201537 #4407] DEBUG -- : Disable-w-typing: n/a

D, [2017-01-28T11:00:42.201604 #4407] DEBUG -- : Accel profiles:   n/a

D, [2017-01-28T11:00:42.201670 #4407] DEBUG -- : 

D, [2017-01-28T11:00:42.201737 #4407] DEBUG -- : Device:           HP WMI hotkeys

D, [2017-01-28T11:00:42.201804 #4407] DEBUG -- : Kernel:           /dev/input/event12

D, [2017-01-28T11:00:42.201880 #4407] DEBUG -- : Group:            7

D, [2017-01-28T11:00:42.201950 #4407] DEBUG -- : Seat:             seat0, default

D, [2017-01-28T11:00:42.202017 #4407] DEBUG -- : Capabilities:     keyboard 

D, [2017-01-28T11:00:42.202083 #4407] DEBUG -- : Tap-to-click:     n/a

D, [2017-01-28T11:00:42.202179 #4407] DEBUG -- : Tap-and-drag:     n/a

D, [2017-01-28T11:00:42.202253 #4407] DEBUG -- : Tap drag lock:    n/a

D, [2017-01-28T11:00:42.202320 #4407] DEBUG -- : Left-handed:      n/a

D, [2017-01-28T11:00:42.202387 #4407] DEBUG -- : Nat.scrolling:    n/a

D, [2017-01-28T11:00:42.202896 #4407] DEBUG -- : Middle emulation: n/a

D, [2017-01-28T11:00:42.202962 #4407] DEBUG -- : Calibration:      n/a

D, [2017-01-28T11:00:42.203022 #4407] DEBUG -- : Scroll methods:   none

D, [2017-01-28T11:00:42.203109 #4407] DEBUG -- : Click methods:    none

D, [2017-01-28T11:00:42.203178 #4407] DEBUG -- : Disable-w-typing: n/a

D, [2017-01-28T11:00:42.203259 #4407] DEBUG -- : Accel profiles:   n/a

D, [2017-01-28T11:00:42.203323 #4407] DEBUG -- : 

D, [2017-01-28T11:00:42.203487 #4407] DEBUG -- : {:libinput_command=>"stdbuf -oL -- libinput-debug-events --enable-dwt --device /dev/input/event5"}

**Comment by Saboteur777** [comment]
Hi, what `libinput-tools` version do you have? This might be related to https://github.com/iberianpig/fusuma/issues/26

**Comment by crpig** [comment]
The libinput-tools version is 1.2.3-1ubuntu1

**Comment by Saboteur777** [comment]
Did you added your user to input group? If yes, did you log out and lag back in?

**Comment by crpig** [comment]
Here is my input group, zdw is current user.
```
~  cat /etc/group | grep input
input:x:106:zdw
```


And I even reboot my notebook, but still the same behaviour.

**Comment by iberianpig** [comment]
@crpig  Do you still have a problem? What are your environment(distribution/version) and Fusuma version?

**Comment by iberianpig** [comment]
Please reopen if you still have a problem. Thank you.

**Comment by Ante994** [comment]
fusuma only working with sudo, whene call without sudu i got this:
`Traceback (most recent call last):
	2: from /usr/bin/fusuma:23:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems.rb:303:in `activate_bin_path'
/usr/lib/ruby/2.5.0/rubygems.rb:284:in `find_spec_for_exe': can't find gem fusuma (>= 0.a) with executable fusuma (Gem::GemNotFoundException)
`
i installed fusuma following instructions, but still not working

**Comment by iberianpig** [comment]
Have you already added $USER to input group then restart session?

**Comment by Ante994** [comment]
yes, `cat /etc/group | grep input` gives `input:x:104:ante`

**Comment by Ante994** [comment]
maybe have something with ruby ? ruby -v gives:
<pre>ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]</pre>

but in error message ruby 2.5.0 is mentioned

**Comment by iberianpig** [comment]
It looks different from the runtime version. Try reinstalling fusuma. And if you use rbenv, try reinstalling without sudo.

**Comment by Ante994** [comment]
after uninstall, and installing folowing instruction i got: `sudo: fusuma: command not found`
also made restart, still not work

it is not installed under /usr/bin

**Comment by Ante994** [comment]
ok, let's say i solved it! i found out install location, it is under `~/.gem/gems/fusuma-0.11.1/exe/` from there fusuma command is executable, now i just setup to run with after boot

@iberianpig tnx for giving feedback

**Comment by iberianpig** [comment]
I'm glad it worked!😄
