### ISSUE TITLE
trouble detecting Left and Right swipes

### ISSUE THREAD

**Issue by marcosfede** [iberianpig/fusuma#31]
First of all thanks for fusuma, it's really useful.

 atm the up and down swipes detect perfectly (with 3 and 4 fingers) but the left and right swipes are really difficult to trigger, I can trigger them maybe 1 out of 20 attempts.

 Is this a know issue or something I can solve from my end?

 I'm running it on a chromebook pixel running elementary OS loki.

**Comment by iberianpig** [comment]
@marcosfede Have you tried to tweak threshold with editing `~/.config/fusuma/config.yml`? (see: https://github.com/iberianpig/fusuma#sample-default-keymap-for-elementary-os)

**Comment by the0demiurge** [comment]
@iberianpig Aatually, it is hard to trigger all gestures even the threshold set to zero. I guess it is because that this software's orientation judging is strict, namely I must swipe very closely vertical or horizontal to trigger that.
I can trigger when 3 or 4 fingers swipe vertically 1 out of 5 attempts.
Ubuntu 16.04
Hope to improve this, thanks!

**Comment by marcosfede** [comment]
@iberianpig tweaking threshold resulted in better detection, thanks!. also I realized I was aligning my fingers vertically to do a horizontal swipe to the left or right,   could that be the problem? If I now align my fingers horizontally when I swipe left or right it triggers much better. (I think this condition could be relaxed a little, since sometimes I don't have my fingers perfectly aligned and then the swipe doesn't trigger)

**Comment by iberianpig** [comment]
It may be caused by libinput-debug-events cannot recognize gestures as swipe.
Please paste a output of `libinput-debug-events` after swiping on touchpad.

**Comment by the0demiurge** [comment]
@iberianpig I just tried these swipes
`event2 	DEVICE_ADDED     Power Button                      seat0 default group1 cap:k
event4 	DEVICE_ADDED     Video Bus                         seat0 default group2 cap:k
event1 	DEVICE_ADDED     Power Button                      seat0 default group3 cap:k
event9 	DEVICE_ADDED     Lenovo EasyCamera                 seat0 default group4 cap:k
event6 	DEVICE_ADDED     RAPOO RAPOO 2.4G Wireless Device  seat0 default group5 cap:k
event7 	DEVICE_ADDED     RAPOO RAPOO 2.4G Wireless Device  seat0 default group6 cap:kp left scroll-nat scroll-button
event8 	DEVICE_ADDED     Ideapad extra buttons             seat0 default group7 cap:k
event3 	DEVICE_ADDED     AT Translated Set 2 keyboard      seat0 default group8 cap:k
event5 	DEVICE_ADDED     SynPS/2 Synaptics TouchPad        seat0 default group9 cap:pg	size 104.43/67.50mm tap(dl off) left scroll-nat scroll-2fg-edge click-buttonareas-clickfinger dwt-on
event5 	POINTER_MOTION    +5.12s	  0.00/ -0.59
event5 	POINTER_MOTION    +5.16s	  0.00/ -0.85
event5 	POINTER_MOTION    +5.17s	  0.00/ -0.19
event5 	POINTER_MOTION    +5.19s	  0.00/ -1.58
event5 	POINTER_MOTION    +5.20s	  0.00/ -3.70
event5 	POINTER_MOTION    +5.21s	  0.00/ -4.01
event5 	POINTER_MOTION    +5.22s	  0.00/ -6.06
event5 	POINTER_MOTION    +5.23s	  0.00/ -8.99
event5 	POINTER_MOTION    +5.24s	 -0.11/-10.51
event5 	POINTER_MOTION    +5.25s	 -0.38/-15.12
event5 	POINTER_MOTION    +5.27s	 -0.37/-21.07
event5 	POINTER_MOTION    +5.29s	 -0.13/-23.32
event5 	POINTER_MOTION    +5.30s	  0.00/-16.26
event5 	POINTER_MOTION    +5.31s	  0.00/ -7.02
event5 	POINTER_MOTION    +5.32s	  0.00/ -3.02
event5 	POINTER_MOTION    +5.35s	  0.00/  1.68
event5 	POINTER_MOTION    +5.36s	 -0.18/  3.49
event5 	POINTER_MOTION    +5.80s	  4.50/  0.76
event5 	POINTER_MOTION    +5.81s	  2.16/  2.20
event5 	POINTER_MOTION    +5.83s	  0.28/  3.63
event5 	POINTER_MOTION    +5.83s	  0.28/  3.82
event5 	POINTER_MOTION    +5.84s	  0.10/  4.28
event5 	POINTER_MOTION    +5.85s	  0.10/  4.48
event5 	POINTER_MOTION    +5.87s	  0.30/  6.46
event5 	POINTER_MOTION    +5.88s	  0.42/  8.76
event5 	POINTER_MOTION    +5.88s	  0.44/  7.29
event5 	POINTER_MOTION    +5.89s	  0.44/  5.99
event5 	POINTER_MOTION    +5.91s	  2.42/  8.07
event5 	POINTER_MOTION    +5.92s	  4.30/  6.95
event5 	POINTER_MOTION    +5.93s	  2.15/  4.69
event5 	POINTER_MOTION    +7.29s	 -4.40/  1.85
event5 	POINTER_MOTION    +7.33s	 -0.46/  1.57
event5 	POINTER_MOTION    +7.35s	  1.85/  0.00
event5 	POINTER_MOTION    +7.36s	  3.00/ -1.21
event5 	POINTER_MOTION    +7.37s	  5.29/ -2.44
event5 	POINTER_MOTION    +7.38s	  6.55/ -1.30
event5 	POINTER_MOTION    +7.39s	 13.02/  0.00
event5 	POINTER_MOTION    +7.40s	 26.66/  0.00
event5 	POINTER_MOTION    +7.41s	 25.01/ -0.29
event5 	POINTER_MOTION    +7.42s	 16.93/ -0.58
event5 	POINTER_MOTION    +7.43s	 15.91/ -0.71
event5 	POINTER_MOTION    +7.44s	 16.15/ -0.84
event5 	POINTER_MOTION    +7.81s	 -2.06/  0.00
event5 	POINTER_MOTION    +7.82s	 -1.75/  0.00
event5 	POINTER_MOTION    +7.83s	 -0.94/  0.00
event5 	POINTER_MOTION    +7.84s	 -0.84/  0.00
event5 	POINTER_MOTION    +7.85s	 -3.28/  0.08
event5 	POINTER_MOTION    +7.86s	 -5.16/  1.82
event5 	POINTER_MOTION    +7.87s	 -5.06/  3.41
event5 	POINTER_MOTION    +7.88s	 -5.25/  1.67
event5 	POINTER_MOTION    +7.89s	 -5.53/  0.00
event5 	POINTER_MOTION    +7.90s	 -8.06/  0.08
event5 	POINTER_MOTION    +7.91s	-11.00/  0.17
event5 	POINTER_MOTION    +7.93s	-12.03/  0.17
event5 	POINTER_MOTION    +7.94s	-13.12/  0.26
event5 	POINTER_MOTION    +7.95s	-11.86/  0.28
event5 	POINTER_MOTION    +7.96s	 -6.75/  0.17
event5 	POINTER_MOTION    +7.97s	 -2.26/  0.00
event5 	POINTER_MOTION    +8.97s	  0.00/ -0.14
event5 	POINTER_AXIS      +9.08s	vert -13.17* horiz -2.06*
event5 	POINTER_AXIS      +9.11s	vert -13.25* horiz -1.08*
event5 	POINTER_AXIS      +9.12s	vert -9.62* horiz -0.05*
event5 	POINTER_AXIS      +9.14s	vert -5.56* horiz 0.89*
event5 	POINTER_AXIS      +9.16s	vert 0.00* horiz 0.00*
event5 	POINTER_AXIS      +9.67s	vert 11.43* horiz 1.27*
event5 	POINTER_AXIS      +9.69s	vert 15.26* horiz 3.75*
event5 	POINTER_AXIS      +9.71s	vert 15.45* horiz 3.37*
event5 	POINTER_AXIS      +9.73s	vert 11.96* horiz 2.16*
event5 	POINTER_AXIS      +9.75s	vert 0.00* horiz 0.00*
event5 	POINTER_MOTION   +10.42s	 -0.07/  0.00
event5 	POINTER_AXIS     +10.49s	vert -0.83* horiz -7.92*
event5 	POINTER_AXIS     +10.51s	vert -2.91* horiz -17.81*
event5 	POINTER_AXIS     +10.54s	vert -1.63* horiz -24.37*
event5 	POINTER_AXIS     +10.56s	vert -0.45* horiz -27.93*
event5 	POINTER_AXIS     +10.58s	vert -0.53* horiz -21.93*
event5 	POINTER_AXIS     +10.60s	vert 0.00* horiz 0.00*
event5 	POINTER_AXIS     +11.07s	vert -2.99* horiz 8.72*
event5 	POINTER_AXIS     +11.09s	vert -3.14* horiz 20.86*
event5 	POINTER_AXIS     +11.11s	vert -0.98* horiz 21.00*
event5 	POINTER_AXIS     +11.13s	vert -0.15* horiz 18.75*
event5 	POINTER_AXIS     +11.15s	vert 0.57* horiz 17.06*
event5 	POINTER_AXIS     +11.16s	vert 0.00* horiz 0.00*
event5 	GESTURE_SWIPE_BEGIN +15.26s	3
event5 	GESTURE_SWIPE_UPDATE +15.26s	3 -3.31/-14.61 (-9.26/-40.88 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +15.28s	3 -2.81/-13.17 (-7.03/-32.93 unaccelerated)
event5 	GESTURE_SWIPE_END +15.32s	3
event5 	GESTURE_SWIPE_BEGIN +16.13s	3
event5 	GESTURE_SWIPE_UPDATE +16.13s	3  3.61/15.45 ( 9.02/38.61 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +16.16s	3  1.83/ 9.88 ( 4.57/24.70 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +16.18s	3  1.69/ 5.26 ( 4.22/13.15 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +16.20s	3  0.19/ 0.15 ( 0.47/ 0.38 unaccelerated)
event5 	GESTURE_SWIPE_END +16.22s	3
event5 	GESTURE_SWIPE_BEGIN +17.06s	3
event5 	GESTURE_SWIPE_UPDATE +17.06s	3 -14.06/-0.04 (-35.15/-0.09 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +17.08s	3 -23.08/-0.09 (-49.45/-0.19 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +17.10s	3 -29.50/ 0.00 (-48.74/ 0.00 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +17.13s	3 -24.84/ 1.23 (-49.68/ 2.46 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +17.15s	3 -26.02/ 2.06 (-52.49/ 4.16 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +17.19s	3 -27.80/ 1.90 (-53.90/ 3.69 unaccelerated)
event5 	GESTURE_SWIPE_END +17.23s	3
event5 	GESTURE_PINCH_BEGIN +17.88s	3
event5 	GESTURE_PINCH_UPDATE +17.88s	3  1.51/ 0.00 ( 3.75/ 0.00 unaccelerated)  1.00 @  0.00
event5 	GESTURE_PINCH_UPDATE +17.90s	3  9.67/-2.55 (24.37/-6.44 unaccelerated)  1.00 @  0.44
event5 	GESTURE_PINCH_UPDATE +17.92s	3  5.62/-0.61 (14.06/-1.51 unaccelerated)  1.01 @  0.23
event5 	GESTURE_PINCH_UPDATE +17.94s	3 14.62/ 0.00 (36.56/ 0.00 unaccelerated)  0.99 @ -0.22
event5 	GESTURE_PINCH_UPDATE +17.96s	3 22.17/ 0.17 (50.62/ 0.38 unaccelerated)  1.02 @  0.40
event5 	GESTURE_PINCH_UPDATE +17.98s	3 28.32/ 3.43 (56.24/ 6.81 unaccelerated)  1.00 @  0.20
event5 	GESTURE_PINCH_UPDATE +18.00s	3 21.85/-4.41 (43.12/-8.71 unaccelerated)  0.99 @  0.53
event5 	GESTURE_PINCH_UPDATE +18.02s	3 14.71/ 0.00 (30.00/ 0.00 unaccelerated)  0.99 @  0.05
event5 	GESTURE_PINCH_UPDATE +18.05s	3  7.17/-0.36 (15.00/-0.76 unaccelerated)  1.01 @  0.21
event5 	GESTURE_PINCH_UPDATE +18.07s	3  6.08/-0.88 (13.12/-1.89 unaccelerated)  0.99 @ -0.01
event5 	GESTURE_PINCH_END +18.10s	3
event5 	POINTER_MOTION   +19.01s	  0.00/  0.28
event5 	POINTER_MOTION   +19.02s	  0.00/  0.87
event5 	GESTURE_SWIPE_BEGIN +20.12s	4
event5 	GESTURE_SWIPE_UPDATE +20.12s	4 -0.79/-9.92 (-2.11/-26.40 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +20.15s	4 -1.50/-12.42 (-3.75/-31.04 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +20.17s	4 -1.97/-9.99 (-4.92/-24.98 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +20.19s	4 -0.84/-5.94 (-2.11/-14.86 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +20.21s	4  0.14/-3.18 ( 0.35/-7.95 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +20.24s	4  0.14/-2.23 ( 0.35/-5.58 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +20.26s	4  0.05/-2.01 ( 0.12/-5.02 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +20.29s	4  0.00/-2.08 ( 0.00/-5.21 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +20.31s	4  0.05/-2.20 ( 0.12/-5.49 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +20.33s	4  0.14/-1.97 ( 0.35/-4.92 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +20.36s	4  0.19/-1.78 ( 0.47/-4.45 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +20.38s	4  0.17/ 0.17 ( 0.47/ 0.47 unaccelerated)
event5 	GESTURE_SWIPE_END +20.41s	4
event5 	GESTURE_PINCH_BEGIN +20.93s	4
event5 	GESTURE_PINCH_UPDATE +20.93s	4  0.14/ 1.99 ( 0.47/ 6.44 unaccelerated)  1.00 @ -0.27
event5 	GESTURE_PINCH_UPDATE +20.96s	4  0.00/ 0.91 ( 0.00/ 2.27 unaccelerated)  1.00 @ -0.11
event5 	GESTURE_PINCH_UPDATE +20.98s	4  0.19/ 8.78 ( 0.47/21.96 unaccelerated)  1.00 @ -1.04
event5 	GESTURE_PINCH_UPDATE +21.00s	4  0.75/ 8.48 ( 1.87/21.20 unaccelerated)  1.00 @ -1.02
event5 	GESTURE_PINCH_UPDATE +21.03s	4  4.69/ 4.39 (11.72/10.98 unaccelerated)  0.99 @ -0.55
event5 	GESTURE_PINCH_UPDATE +21.05s	4 -3.56/ 7.57 (-8.91/18.93 unaccelerated)  0.98 @ -0.02
event5 	GESTURE_PINCH_UPDATE +21.07s	4  3.19/ 8.48 ( 7.97/21.20 unaccelerated)  0.99 @  0.04
event5 	GESTURE_PINCH_UPDATE +21.09s	4  4.50/ 7.88 (11.25/19.69 unaccelerated)  0.98 @  0.01
event5 	GESTURE_PINCH_UPDATE +21.12s	4  0.19/ 5.45 ( 0.47/13.63 unaccelerated)  0.98 @ -0.51
event5 	GESTURE_PINCH_UPDATE +21.14s	4  0.19/ 7.87 ( 0.47/19.69 unaccelerated)  0.98 @  0.07
event5 	GESTURE_PINCH_UPDATE +21.16s	4  4.87/ 7.87 (12.19/19.69 unaccelerated)  0.97 @ -0.00
event5 	GESTURE_PINCH_UPDATE +21.19s	4  0.00/ 3.63 ( 0.00/ 9.09 unaccelerated)  0.97 @  0.44
event5 	GESTURE_PINCH_UPDATE +21.21s	4  0.00/-1.82 ( 0.00/-4.54 unaccelerated)  0.97 @  0.37
event5 	GESTURE_PINCH_END +21.24s	4
event5 	GESTURE_SWIPE_BEGIN +21.76s	4
event5 	GESTURE_SWIPE_UPDATE +21.76s	4 -6.56/ 1.63 (-16.40/ 4.07 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +21.79s	4 -6.23/ 0.61 (-15.58/ 1.51 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +21.81s	4 -5.11/-0.23 (-12.77/-0.57 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +21.83s	4 -5.25/-0.11 (-13.12/-0.28 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +21.86s	4 -5.44/-0.08 (-13.59/-0.19 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +21.88s	4 -7.83/-0.91 (-19.57/-2.27 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +21.90s	4 -9.89/-2.08 (-24.72/-5.21 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +21.93s	4 -9.56/-2.65 (-23.90/-6.62 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +21.95s	4 -7.31/-3.86 (-18.28/-9.65 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +21.97s	4 -4.69/-3.86 (-11.72/-9.65 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +22.00s	4 -5.62/-1.67 (-14.06/-4.16 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +22.02s	4 -4.55/-0.34 (-11.37/-0.85 unaccelerated)
event5 	GESTURE_SWIPE_END +22.07s	4
event5 	GESTURE_SWIPE_BEGIN +22.60s	4
event5 	GESTURE_SWIPE_UPDATE +22.60s	4  7.36/-0.95 (18.40/-2.37 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +22.62s	4  5.16/-1.63 (12.89/-4.07 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +22.64s	4  6.00/-0.11 (15.00/-0.28 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +22.67s	4  7.73/-0.91 (19.33/-2.27 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +22.69s	4  8.72/-1.89 (21.79/-4.73 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +22.71s	4  8.53/-1.21 (21.33/-3.03 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +22.74s	4  8.34/ 0.87 (20.86/ 2.18 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +22.76s	4 10.59/ 3.07 (26.48/ 7.67 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +22.79s	4 12.28/ 2.95 (30.70/ 7.38 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +22.81s	4 11.44/ 0.98 (28.59/ 2.46 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +22.83s	4 10.87/ 0.04 (27.18/ 0.09 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +22.86s	4 10.17/-0.04 (25.43/-0.09 unaccelerated)
event5 	GESTURE_SWIPE_UPDATE +22.88s	4  7.03/-0.04 (17.58/-0.09 unaccelerated)
event5 	GESTURE_SWIPE_END +22.91s	4
event5 	GESTURE_PINCH_BEGIN +28.99s	2
event5 	GESTURE_PINCH_UPDATE +28.99s	2  2.77/ 0.28 ( 7.50/ 0.76 unaccelerated)  1.05 @  1.38
event5 	GESTURE_PINCH_UPDATE +29.01s	2  2.91/ 0.00 (10.78/ 0.00 unaccelerated)  1.06 @  1.05
event5 	GESTURE_PINCH_UPDATE +29.04s	2  0.29/-0.12 ( 0.94/-0.38 unaccelerated)  1.07 @  0.04
event5 	GESTURE_PINCH_UPDATE +29.05s	2  2.99/ 1.14 ( 8.91/ 3.41 unaccelerated)  1.12 @  0.24
event5 	GESTURE_PINCH_UPDATE +29.07s	2 -0.55/ 2.39 (-1.41/ 6.06 unaccelerated)  1.13 @ -0.24
event5 	GESTURE_PINCH_UPDATE +29.09s	2  2.81/-0.45 ( 7.03/-1.14 unaccelerated)  1.16 @  1.77
event5 	GESTURE_PINCH_UPDATE +29.11s	2  0.19/-4.09 ( 0.47/-10.22 unaccelerated)  1.18 @ -0.50
event5 	GESTURE_PINCH_UPDATE +29.14s	2  4.12/-2.27 (10.31/-5.68 unaccelerated)  1.20 @  0.45
event5 	GESTURE_PINCH_UPDATE +29.16s	2  0.70/-0.42 ( 1.87/-1.14 unaccelerated)  1.21 @  0.06
event5 	GESTURE_PINCH_UPDATE +29.18s	2  3.86/-3.26 (10.31/-8.71 unaccelerated)  1.24 @  0.50
event5 	GESTURE_PINCH_UPDATE +29.20s	2 -0.17/-0.14 (-0.47/-0.38 unaccelerated)  1.24 @  0.09
event5 	GESTURE_PINCH_UPDATE +29.22s	2  4.58/-0.27 (12.65/-0.76 unaccelerated)  1.25 @  0.93
event5 	GESTURE_PINCH_UPDATE +29.24s	2  4.50/-0.91 (11.25/-2.27 unaccelerated)  1.29 @  0.04
event5 	GESTURE_PINCH_UPDATE +29.26s	2  0.19/ 0.00 ( 0.47/ 0.00 unaccelerated)  1.29 @  0.03
event5 	GESTURE_PINCH_UPDATE +29.31s	2 -0.32/ 0.00 (-0.94/ 0.00 unaccelerated)  1.30 @  0.07
event5 	GESTURE_PINCH_UPDATE +29.32s	2 -0.08/ 0.06 (-0.47/ 0.38 unaccelerated)  1.30 @  0.08
event5 	GESTURE_PINCH_UPDATE +29.35s	2  0.08/ 0.00 ( 0.47/ 0.00 unaccelerated)  1.30 @  0.03
event5 	GESTURE_PINCH_UPDATE +29.37s	2  0.61/ 0.00 ( 2.81/ 0.00 unaccelerated)  1.32 @  1.47
event5 	GESTURE_PINCH_UPDATE +29.39s	2  0.12/ 0.10 ( 0.47/ 0.38 unaccelerated)  1.32 @  0.01
event5 	GESTURE_PINCH_UPDATE +29.41s	2 -0.87/ 4.22 (-2.34/11.36 unaccelerated)  1.34 @ -0.31
event5 	GESTURE_PINCH_END +29.43s	2
event5 	POINTER_MOTION   +30.01s	 -5.06/  0.00
event5 	POINTER_MOTION   +30.02s	 -3.00/  0.00
event5 	POINTER_MOTION   +30.04s	 -0.75/  0.00
event5 	POINTER_MOTION   +30.05s	 -0.75/  0.00
event5 	GESTURE_PINCH_BEGIN +30.18s	2
event5 	GESTURE_PINCH_UPDATE +30.18s	2  0.33/ 0.00 ( 0.94/ 0.00 unaccelerated)  1.00 @  0.00
event5 	GESTURE_PINCH_UPDATE +30.21s	2  2.37/ 1.76 (11.25/ 8.33 unaccelerated)  0.99 @ -0.06
event5 	GESTURE_PINCH_UPDATE +30.23s	2 -0.52/ 0.00 (-1.87/ 0.00 unaccelerated)  0.99 @ -0.10
event5 	GESTURE_PINCH_UPDATE +30.25s	2 -0.35/ 0.09 (-1.41/ 0.38 unaccelerated)  0.98 @ -0.07
event5 	GESTURE_PINCH_UPDATE +30.27s	2  4.37/ 0.00 (11.72/ 0.00 unaccelerated)  0.98 @ -0.46
event5 	GESTURE_PINCH_UPDATE +30.29s	2  0.00/ 0.14 ( 0.00/ 0.38 unaccelerated)  0.98 @  0.02
event5 	GESTURE_PINCH_UPDATE +30.31s	2 -0.08/ 0.06 (-0.47/ 0.38 unaccelerated)  0.97 @ -0.04
event5 	GESTURE_PINCH_UPDATE +30.33s	2  3.57/ 2.61 ( 9.84/ 7.19 unaccelerated)  0.96 @ -0.08
event5 	GESTURE_PINCH_UPDATE +30.35s	2  0.17/ 0.00 ( 0.47/ 0.00 unaccelerated)  0.96 @  0.01
event5 	GESTURE_PINCH_UPDATE +30.37s	2 -0.17/-2.58 (-0.47/-7.19 unaccelerated)  0.95 @  0.25
event5 	GESTURE_PINCH_UPDATE +30.39s	2  0.53/-0.43 ( 1.41/-1.14 unaccelerated)  0.95 @ -0.04
event5 	GESTURE_PINCH_UPDATE +30.42s	2  1.01/-3.67 ( 2.81/-10.22 unaccelerated)  0.92 @ -0.34
event5 	GESTURE_PINCH_UPDATE +30.44s	2  3.75/ 3.03 ( 9.37/ 7.57 unaccelerated)  0.91 @ -0.01
event5 	GESTURE_PINCH_UPDATE +30.46s	2  0.00/-2.73 ( 0.00/-6.81 unaccelerated)  0.91 @  0.29
event5 	GESTURE_PINCH_UPDATE +30.48s	2 -0.34/ 0.00 (-0.94/ 0.00 unaccelerated)  0.91 @ -0.00
event5 	GESTURE_PINCH_UPDATE +30.50s	2 -0.09/ 0.07 (-0.47/ 0.38 unaccelerated)  0.91 @ -0.04
event5 	GESTURE_PINCH_UPDATE +30.52s	2 -2.37/ 3.41 (-6.56/ 9.46 unaccelerated)  0.89 @ -0.03
event5 	GESTURE_PINCH_UPDATE +30.54s	2  3.94/ 0.15 ( 9.84/ 0.38 unaccelerated)  0.88 @ -0.38
event5 	GESTURE_PINCH_UPDATE +30.56s	2 -0.53/ 0.14 (-1.41/ 0.38 unaccelerated)  0.88 @ -0.08
event5 	GESTURE_PINCH_UPDATE +30.58s	2 -4.20/-0.14 (-11.25/-0.38 unaccelerated)  0.87 @ -0.41
event5 	GESTURE_PINCH_UPDATE +30.60s	2 -0.56/ 0.30 (-1.41/ 0.76 unaccelerated)  0.87 @  0.00
event5 	GESTURE_PINCH_UPDATE +30.63s	2 -4.31/ 3.18 (-10.78/ 7.95 unaccelerated)  0.86 @ -0.29
event5 	GESTURE_PINCH_UPDATE +30.65s	2 -0.56/ 0.15 (-1.41/ 0.38 unaccelerated)  0.84 @ -0.90
event5 	GESTURE_PINCH_UPDATE +30.67s	2  0.16/ 0.00 ( 0.47/ 0.00 unaccelerated)  0.84 @ -0.02
event5 	GESTURE_PINCH_END +30.68s	2
event3 	KEYBOARD_KEY     +34.26s	KEY_LEFTCTRL (29) pressed
event3 	KEYBOARD_KEY     +34.48s	KEY_C (46) pressed
event3 	KEYBOARD_KEY     +34.66s	KEY_C (46) released
event3 	KEYBOARD_KEY     +34.67s	KEY_LEFTCTRL (29) released
event7 	POINTER_BUTTON   +36.67s	BTN_LEFT (272) pressed, seat count: 1
event7 	POINTER_BUTTON   +36.77s	BTN_LEFT (272) released, seat count: 0
event7 	POINTER_MOTION   +37.39s	 -0.31/ -0.31
event7 	POINTER_MOTION   +37.40s	 -2.68/ -1.79
event7 	POINTER_MOTION   +37.41s	 -3.17/ -2.11
event7 	POINTER_MOTION   +37.42s	 -1.01/  0.00
event7 	POINTER_MOTION   +37.42s	 -3.00/ -2.00
event7 	POINTER_MOTION   +37.43s	 -2.00/ -1.00
event7 	POINTER_MOTION   +37.44s	 -1.00/  0.00
event7 	POINTER_MOTION   +37.45s	 -1.00/ -1.00
event7 	POINTER_MOTION   +37.46s	 -1.00/  0.00
event7 	POINTER_MOTION   +37.48s	 -1.00/  0.00
event7 	POINTER_BUTTON   +37.65s	BTN_LEFT (272) pressed, seat count: 1
event7 	POINTER_BUTTON   +37.74s	BTN_LEFT (272) released, seat count: 0
event3 	KEYBOARD_KEY     +38.37s	KEY_LEFTCTRL (29) pressed
event3 	KEYBOARD_KEY     +38.51s	KEY_C (46) pressed
`
and here is my config file
`swipe:
  3: 
    left: 
      shortcut: 'ctrl+tab'
    right: 
      shortcut: 'ctrl+shift+tab'
    up: 
      shortcut: 'ctrl+super+Up'
    down: 
      shortcut: 'ctrl+super+Down'
  4:
    left: 
      shortcut: 'alt+tab'
    right: 
      shortcut: 'alt+shift+tab'
    up: 
      shortcut: 'ctrl+alt+Down'
    down: 
      shortcut: 'ctrl+alt+Up'
pinch:
  in:
    shortcut: 'ctrl+plus'
  out:
     shortcut: 'ctrl+minus'

threshold:
  swipe: 0
  pinch: 0.5
`

**Comment by LitterChen** [comment]
Firstly thanks for fusuma.
But it is hard to trigger even the threshold set to small such as 0.1. I find the triggers will be better if I swipe 3 or 4 fingers after swipe 2 fingers.if I want continuous swipe to touch off a sequence shortcut.The triggers will be not good. 
Hope to improve this, thanks!

**Comment by the0demiurge** [comment]
I found a solution to this problem by accidently run fusuma with root privileges, if not with root privileges, the fusuma may not work reliably with many consequences. However, it is also not very sensitive when swiping left/right.

**Comment by iberianpig** [comment]
@LitterChen The option is added for tweaking an interval until next a swipe/pinch with ver0.3.0.
Please try with updating fusuma.

**Comment by MisterPresident** [comment]
I am having problems detecting 5-finger actions (if I run `fusuma -v` it tells me that i just use 4 fingers but doesn't perform 4-finger action too.
`libinput-debug-events` doesn't show anything when i preform a 5 finger swipe but with your old pear script xSwipe my 5 finger swipe works.
Do you have a tip for me?

**Comment by iberianpig** [comment]
@MisterPresident Thank you for using my tools.
It indicates libinput drivers' detect up to 4 fingers. This issue may be libinput driver's issue.
