### ISSUE TITLE
don't work on Arch linux

### ISSUE THREAD

**Issue by fadri14** [iberianpig/fusuma#327]
Hello, I use fusuma on arch linux with wayland for months but since the update of November 24, 2024 it does not work. Fusuma is in the latest version. There are no error messages in the fusuma logs.

```
Fusuma: 3.6.2
libinput: 1.27.0
ruby 3.3.5p100
```
Thanks, for help. I like this project.

**Comment by iberianpig** [comment]
@fadri14  Please update fusuma version to v3.7.0 that support libinput 1.27.0 format.

see: https://github.com/iberianpig/fusuma/issues/324

**Comment by fadri14** [comment]
Nice thank you very much
