### ISSUE TITLE
Maybe add info that you need to restart?

### ISSUE THREAD

**Issue by Gotterbild** [iberianpig/fusuma#33]
Hey, Thanx for fantastic job! Everything works great, but I had an issue with input group rights initially.

I followed steps from [here](https://github.com/iberianpig/fusuma) exactly, but nothing worked when I finally typed `fusuma`.

Wanted to add an issue about that, but saw issue #32 and found your comment with `libinput-debug-events` command. Typed that and saw that the problem is with permissions. But I typed `sudo gpasswd -a $USER input` before installing...

Problem was solved with simple reboot. So, maybe add info about `libinput-debug-events` for debugging and info that you need to restart  in main `readme.md` file? I think people will appreciate that. For me it would save 15-20 minutes of time.

Thanks for your work again! Good luck! Best wishes!

**Comment by iberianpig** [comment]
Thanks for your kind suggestion!
I will update README.
