### ISSUE TITLE
How about adding adjustable interval threshold?

### ISSUE THREAD

**Issue by joshuatshaffer** [iberianpig/fusuma#35]
I would like the option to make gestures in rapid succession. I am using Fusuma for switching workspaces in a similar fashion to macOS. I really like Fusuma because it gives me a very quick way to move between several desktops, but it is annoying to have to wait a half second between swipes.

**Comment by 2edff206** [comment]
I installed fusuma today because Touchegg doesn't work anymore on 17.04.
I was about to make the same request, I am glad someone had the same idea ! It's annoying to have to wait to switch multiple workspaces

Thanks for your work

**Comment by 2edff206** [comment]
Ok I solved it myself. For info you just have to edit this file /var/lib/gems/2.3.0/gems/fusuma-0.2.7/lib/fusuma/swipe.rb
Near the beginning of the file change INTERVAL=0.5 to INTERVAL=0.1

**Comment by joshuatshaffer** [comment]
Ah, great! Yeah, I'm also using this because Ubuntu 17.04 killed Touchégg. Thanks for the work around. Still, I think this is a good candidate for a new config option.

**Comment by joshuatshaffer** [comment]
I went ahead and added this feature my self. The changes are in pull request #36. I hope I did everything alright. This is my first time using ruby and my first time contributing to a real project.

**Comment by iberianpig** [comment]
@joshuatshaffer Thanks a lot for your PR!
