### ISSUE TITLE
Alternative actions (not just keyboard shortcuts)

### ISSUE THREAD

**Issue by bvarner** [iberianpig/fusuma#39]
So I'm accustomed to three-finger click n' drag (mouse down, mouse move on update, mouse up at gesture end) and I think fusuma is a really nice way of tracking this.

of the things I've looked into so far, this was the easiest one to get 'running' on debian stretch.

It looks like it might be trivial to update the xdotool calls and configuration with an actiontype. Thoughts on this? Would you entertain PRs for this?

**Comment by iberianpig** [comment]
It's difficult to recognize 3 fingers click and drag from libinput driver.
