### ISSUE TITLE
input from multiple devices

### ISSUE THREAD

**Issue by diraimondo** [iberianpig/fusuma#4]
I'm using the internal touchpad of my laptop but, in the office, I use also an Apple Magic Trackpad (connected on demand using bluetooth). It could be useful to add an option to launch `libinput-debug-events` without any device specifications: fusuma would receive gestures from all the available devices (also the one connected after its launch).

**Comment by iberianpig** [comment]
Hi @diraimondo. 

Thank you for your report and suggestion.
I bought external touchpad and confirmed this issue. :)

I updated Fusuma to recognize multi devices on version 0.2.5.
Please update fusuma

```
$ gem update fusuma
```

Thank you.
