### ISSUE TITLE
How to bind multimedia key?

### ISSUE THREAD

**Issue by ahmadmuzakki29** [iberianpig/fusuma#44]
hi guys this lib is awesome. but how we bind the key that not in our keyboard. I mean I want to bind Audio play to some gesture. I know I can put shortcut to Audio play with some key then bind that key with fusuma. But is it possible to directly do an input of Audio play or Audio next?

**Comment by ahmadmuzakki29** [comment]
and can it detect 4 finger tap?

**Comment by iberianpig** [comment]
See (http://wiki.linuxquestions.org/wiki/XF86_keyboard_symbols).

> and can it detect 4 finger tap?

it cannot detect tap event with libinput-debug-events.
