### ISSUE TITLE
How to autostart fusuma in the background on login?

### ISSUE THREAD

**Issue by Rodancoci** [iberianpig/fusuma#46]
I'm running Unity on Ubuntu 17.04.

So far I've been manually running
`$ fusuma & disown`
And then closing the terminal, which works well enough.

However, I wish I could get fusuma to run by itself whenever I login. I've tried adding the command 'fusuma'  to Ubuntu's "Startup Applications" without success. Upon rebooting and logging in neither fusuma nor ruby are running.

Any suggestions?

**Comment by iberianpig** [comment]
@Rodancoci 

You can find  correct path with below command.
```
$ which fusuma
```

then please register the path you found and try restart.

**Comment by Rodancoci** [comment]
I tried setting the full path output by
`$ which fusuma`
As the command on the startup item but I got the same result.

Launching the full path manually from the terminal after logging in works, however.

**Comment by iberianpig** [comment]
Please record log and check it on your environment.
`path/to/your/fusuma -v > /tmp/fusuma.log`
restart your machine, then `cat /tmp/fsuma.log`

**Comment by Rodancoci** [comment]
Here are the contents of the log: https://pastebin.com/MNcQ7Mgp

**Comment by Rodancoci** [comment]
I managed to get it working how I wanted. What finally worked for me was adding the following line at the end of `~/.profile`:
`/home/usr/.rvm/gems/ruby-2.4.0/wrappers/fusuma & disown`

**Comment by kontrollanten** [comment]
Thanks @Rodancoci for the help. I got it working with the following command.
`printf "$(which fusuma) & disown \n" >> .profile`

But .profile doesn't feel like the natural place for this command, even if it works. I'm pretty new into Linux, but wouldn't it be better if the application created a script in init.d? Then it would be more of a plug n play application.

**Comment by iberianpig** [comment]
@kontrollanten Oh, that's a nice idea. Could you make the pull-request?

**Comment by kontrollanten** [comment]
I'm new into both ruby and Linux. But I'll give it some tries.

**Comment by worldofpeace** [comment]
What about people who use zsh etc.?

**Comment by rmasclef** [comment]
@Rodancoci in a more user friendly way, you can use `startup application preferences` to start any software you want at user login.

For example, I added `firefox`, `slack` and `fusuma` in order to start those three apps when I login.

**Comment by ouzc12358** [comment]
@rmasclef  thanks! simple and useful ! it takes my 2 days

**Comment by JafarBadour** [comment]
I am using ubuntu 19
When I add fusuma to startup applications It doesnt work. However when I run 
```
sudo fusuma &> dev/null
```

It works perfectly. 

I tried this one 
![image](https://user-images.githubusercontent.com/16943355/79229862-625c3800-7e6c-11ea-9c4e-e5c39559458a.png)

and this one:
![image](https://user-images.githubusercontent.com/16943355/79229894-6f792700-7e6c-11ea-8991-465c6148907a.png)

Neither works, i think because it doesnt accept sudo but I dont know how to fix!

**Comment by iberianpig** [comment]
Please try adding $USER to input group and configure autostart without sudo.

**Comment by JafarBadour** [comment]
I am not sure how is that possible? how can I add $USER ?

**Comment by iberianpig** [comment]
Please read README.

https://github.com/iberianpig/fusuma/blob/master/README.md#autostart-gnome-session-properties

**Comment by JafarBadour** [comment]
Yep this worked for me

## Autostart (gnome-session-properties)
Check the path where you installed fusuma with $ which fusuma
Open ```$ gnome-session-properties```
Add ```Fusuma``` and enter the location where the above path was checked in the command input field
Add the ```-d``` option at the end of the command input field

## Screenshot of the configuration on my device

![image](https://user-images.githubusercontent.com/16943355/79241518-d3efb280-7e7b-11ea-89d5-4a0a54ef8b7e.png)

**Comment by athulkrishna2015** [comment]
> Yep this worked for me, thanks!!
> ## Autostart (gnome-session-properties)
> 
> Check the path where you installed fusuma with $ which fusuma
> Open `$ gnome-session-properties`
> Add `Fusuma` and enter the location where the above path was checked in the command input field
> Add the `-d` option at the end of the command input field
> ## Screenshot of the configuration on my device
> 
> ![image](https://user-images.githubusercontent.com/16943355/79241518-d3efb280-7e7b-11ea-89d5-4a0a54ef8b7e.png)

what is the meaning of `-d`

**Comment by JafarBadour** [comment]
I think -d is for detached mode @athulkrishna2015
