### ISSUE TITLE
support for xdotool other actions

### ISSUE THREAD

**Issue by diraimondo** [iberianpig/fusuma#5]
I'm actually using libinput-gestures with actions not actually supported by fusuma. It would be nice to support them too.
For example I'm using `xdotool set_desktop --relative -- +1` and `xdotool set_desktop --relative -- -1` to scroll among the desktop spaces. 
It would be great also to support generic commands.

**Comment by iberianpig** [comment]
Please try `xbindkeys` and assign the command. 
I want to keep it simple.
