### ISSUE TITLE
ubuntu 16.04

### ISSUE THREAD

**Issue by zhanbinHo** [iberianpig/fusuma#53]
Run command fusuma Then show this error :
D, [2017-11-19T14:31:44.543822 #10885] DEBUG -- : Accel profiles:   n/a

D, [2017-11-19T14:31:44.543867 #10885] DEBUG -- : Rotation:         n/a

D, [2017-11-19T14:31:44.543912 #10885] DEBUG -- : 

D, [2017-11-19T14:31:44.544001 #10885] DEBUG -- : {:libinput_command=>"stdbuf -oL -- libinput-debug-events --enable-dwt "}
/var/lib/gems/2.3.0/gems/fusuma-0.3.3/lib/fusuma.rb:37:in `each': Interrupt
	from /var/lib/gems/2.3.0/gems/fusuma-0.3.3/lib/fusuma.rb:37:in `block in read_libinput'
	from /usr/lib/ruby/2.3.0/open3.rb:205:in `popen_run'
	from /usr/lib/ruby/2.3.0/open3.rb:95:in `popen3'
	from /var/lib/gems/2.3.0/gems/fusuma-0.3.3/lib/fusuma.rb:36:in `read_libinput'
	from /var/lib/gems/2.3.0/gems/fusuma-0.3.3/lib/fusuma.rb:21:in `run'
	from /var/lib/gems/2.3.0/gems/fusuma-0.3.3/exe/fusuma:21:in `<top (required)>'
	from /usr/local/bin/fusuma:23:in `load'
	from /usr/local/bin/fusuma:23:in `<main>'

**Comment by lqfxz520** [comment]
D, [2017-11-22T15:02:29.543847 #30935] DEBUG -- : Device:           Power Button

D, [2017-11-22T15:02:29.544067 #30935] DEBUG -- : Kernel:           /dev/input/event2

D, [2017-11-22T15:02:29.544216 #30935] DEBUG -- : Group:            1

D, [2017-11-22T15:02:29.544371 #30935] DEBUG -- : Seat:             seat0, default

D, [2017-11-22T15:02:29.544437 #30935] DEBUG -- : Capabilities:     keyboard 

D, [2017-11-22T15:02:29.544508 #30935] DEBUG -- : Tap-to-click:     n/a

D, [2017-11-22T15:02:29.544563 #30935] DEBUG -- : Tap-and-drag:     n/a

D, [2017-11-22T15:02:29.544624 #30935] DEBUG -- : Tap drag lock:    n/a

D, [2017-11-22T15:02:29.544676 #30935] DEBUG -- : Left-handed:      n/a

D, [2017-11-22T15:02:29.544739 #30935] DEBUG -- : Nat.scrolling:    n/a

D, [2017-11-22T15:02:29.544810 #30935] DEBUG -- : Middle emulation: n/a

D, [2017-11-22T15:02:29.544873 #30935] DEBUG -- : Calibration:      n/a

D, [2017-11-22T15:02:29.544942 #30935] DEBUG -- : Scroll methods:   none

D, [2017-11-22T15:02:29.545009 #30935] DEBUG -- : Click methods:    none

D, [2017-11-22T15:02:29.545074 #30935] DEBUG -- : Disable-w-typing: n/a

D, [2017-11-22T15:02:29.545137 #30935] DEBUG -- : Accel profiles:   n/a

D, [2017-11-22T15:02:29.545202 #30935] DEBUG -- : Rotation:         n/a

D, [2017-11-22T15:02:29.545267 #30935] DEBUG -- : 

D, [2017-11-22T15:02:29.545334 #30935] DEBUG -- : Device:           Video Bus

D, [2017-11-22T15:02:29.545400 #30935] DEBUG -- : Kernel:           /dev/input/event4

D, [2017-11-22T15:02:29.545477 #30935] DEBUG -- : Group:            2

D, [2017-11-22T15:02:29.545538 #30935] DEBUG -- : Seat:             seat0, default

D, [2017-11-22T15:02:29.545603 #30935] DEBUG -- : Capabilities:     keyboard 

D, [2017-11-22T15:02:29.545724 #30935] DEBUG -- : Tap-to-click:     n/a

D, [2017-11-22T15:02:29.545790 #30935] DEBUG -- : Tap-and-drag:     n/a

D, [2017-11-22T15:02:29.545853 #30935] DEBUG -- : Tap drag lock:    n/a

D, [2017-11-22T15:02:29.545915 #30935] DEBUG -- : Left-handed:      n/a

D, [2017-11-22T15:02:29.545978 #30935] DEBUG -- : Nat.scrolling:    n/a

D, [2017-11-22T15:02:29.546047 #30935] DEBUG -- : Middle emulation: n/a

D, [2017-11-22T15:02:29.546110 #30935] DEBUG -- : Calibration:      n/a

D, [2017-11-22T15:02:29.546182 #30935] DEBUG -- : Scroll methods:   none

D, [2017-11-22T15:02:29.546264 #30935] DEBUG -- : Click methods:    none

D, [2017-11-22T15:02:29.546342 #30935] DEBUG -- : Disable-w-typing: n/a

D, [2017-11-22T15:02:29.546396 #30935] DEBUG -- : Accel profiles:   n/a

D, [2017-11-22T15:02:29.546472 #30935] DEBUG -- : Rotation:         n/a

D, [2017-11-22T15:02:29.546546 #30935] DEBUG -- : 

D, [2017-11-22T15:02:29.546621 #30935] DEBUG -- : Device:           Power Button

D, [2017-11-22T15:02:29.546696 #30935] DEBUG -- : Kernel:           /dev/input/event1

D, [2017-11-22T15:02:29.546782 #30935] DEBUG -- : Group:            3

D, [2017-11-22T15:02:29.546868 #30935] DEBUG -- : Seat:             seat0, default

D, [2017-11-22T15:02:29.546980 #30935] DEBUG -- : Capabilities:     keyboard 

D, [2017-11-22T15:02:29.547063 #30935] DEBUG -- : Tap-to-click:     n/a

D, [2017-11-22T15:02:29.547144 #30935] DEBUG -- : Tap-and-drag:     n/a

D, [2017-11-22T15:02:29.547217 #30935] DEBUG -- : Tap drag lock:    n/a

D, [2017-11-22T15:02:29.547287 #30935] DEBUG -- : Left-handed:      n/a

D, [2017-11-22T15:02:29.547356 #30935] DEBUG -- : Nat.scrolling:    n/a

D, [2017-11-22T15:02:29.547410 #30935] DEBUG -- : Middle emulation: n/a

D, [2017-11-22T15:02:29.547454 #30935] DEBUG -- : Calibration:      n/a

D, [2017-11-22T15:02:29.547494 #30935] DEBUG -- : Scroll methods:   none

D, [2017-11-22T15:02:29.547534 #30935] DEBUG -- : Click methods:    none

D, [2017-11-22T15:02:29.547573 #30935] DEBUG -- : Disable-w-typing: n/a

D, [2017-11-22T15:02:29.547678 #30935] DEBUG -- : Accel profiles:   n/a

D, [2017-11-22T15:02:29.547718 #30935] DEBUG -- : Rotation:         n/a

D, [2017-11-22T15:02:29.547758 #30935] DEBUG -- : 

D, [2017-11-22T15:02:29.547798 #30935] DEBUG -- : Device:           Lid Switch

D, [2017-11-22T15:02:29.547839 #30935] DEBUG -- : Kernel:           /dev/input/event0

D, [2017-11-22T15:02:29.547889 #30935] DEBUG -- : Group:            4

D, [2017-11-22T15:02:29.547931 #30935] DEBUG -- : Seat:             seat0, default

D, [2017-11-22T15:02:29.547975 #30935] DEBUG -- : Capabilities:     

D, [2017-11-22T15:02:29.548015 #30935] DEBUG -- : Tap-to-click:     n/a

D, [2017-11-22T15:02:29.548056 #30935] DEBUG -- : Tap-and-drag:     n/a

D, [2017-11-22T15:02:29.548096 #30935] DEBUG -- : Tap drag lock:    n/a

D, [2017-11-22T15:02:29.548135 #30935] DEBUG -- : Left-handed:      n/a

D, [2017-11-22T15:02:29.548186 #30935] DEBUG -- : Nat.scrolling:    n/a

D, [2017-11-22T15:02:29.548231 #30935] DEBUG -- : Middle emulation: n/a

D, [2017-11-22T15:02:29.548273 #30935] DEBUG -- : Calibration:      n/a

D, [2017-11-22T15:02:29.548315 #30935] DEBUG -- : Scroll methods:   none

D, [2017-11-22T15:02:29.548356 #30935] DEBUG -- : Click methods:    none

D, [2017-11-22T15:02:29.548396 #30935] DEBUG -- : Disable-w-typing: n/a

D, [2017-11-22T15:02:29.548435 #30935] DEBUG -- : Accel profiles:   n/a

D, [2017-11-22T15:02:29.548474 #30935] DEBUG -- : Rotation:         n/a

D, [2017-11-22T15:02:29.548514 #30935] DEBUG -- : 

D, [2017-11-22T15:02:29.548554 #30935] DEBUG -- : Device:           HDA Intel HDMI HDMI/DP,pcm=3

D, [2017-11-22T15:02:29.548596 #30935] DEBUG -- : Kernel:           /dev/input/event9

D, [2017-11-22T15:02:29.548643 #30935] DEBUG -- : Group:            5

D, [2017-11-22T15:02:29.548685 #30935] DEBUG -- : Seat:             seat0, default

D, [2017-11-22T15:02:29.548726 #30935] DEBUG -- : Capabilities:     

D, [2017-11-22T15:02:29.548767 #30935] DEBUG -- : Tap-to-click:     n/a

D, [2017-11-22T15:02:29.548812 #30935] DEBUG -- : Tap-and-drag:     n/a

D, [2017-11-22T15:02:29.548852 #30935] DEBUG -- : Tap drag lock:    n/a

D, [2017-11-22T15:02:29.548892 #30935] DEBUG -- : Left-handed:      n/a

D, [2017-11-22T15:02:29.548955 #30935] DEBUG -- : Nat.scrolling:    n/a

D, [2017-11-22T15:02:29.549000 #30935] DEBUG -- : Middle emulation: n/a

D, [2017-11-22T15:02:29.549042 #30935] DEBUG -- : Calibration:      n/a

D, [2017-11-22T15:02:29.549082 #30935] DEBUG -- : Scroll methods:   none

D, [2017-11-22T15:02:29.549122 #30935] DEBUG -- : Click methods:    none

D, [2017-11-22T15:02:29.549163 #30935] DEBUG -- : Disable-w-typing: n/a

D, [2017-11-22T15:02:29.549203 #30935] DEBUG -- : Accel profiles:   n/a

D, [2017-11-22T15:02:29.549242 #30935] DEBUG -- : Rotation:         n/a

D, [2017-11-22T15:02:29.549292 #30935] DEBUG -- : 

D, [2017-11-22T15:02:29.549359 #30935] DEBUG -- : Device:           HDA Intel HDMI HDMI/DP,pcm=7

D, [2017-11-22T15:02:29.549457 #30935] DEBUG -- : Kernel:           /dev/input/event10

D, [2017-11-22T15:02:29.549512 #30935] DEBUG -- : Group:            5

D, [2017-11-22T15:02:29.549559 #30935] DEBUG -- : Seat:             seat0, default

D, [2017-11-22T15:02:29.549606 #30935] DEBUG -- : Capabilities:     

D, [2017-11-22T15:02:29.549652 #30935] DEBUG -- : Tap-to-click:     n/a

D, [2017-11-22T15:02:29.549698 #30935] DEBUG -- : Tap-and-drag:     n/a

D, [2017-11-22T15:02:29.549750 #30935] DEBUG -- : Tap drag lock:    n/a

D, [2017-11-22T15:02:29.549796 #30935] DEBUG -- : Left-handed:      n/a

D, [2017-11-22T15:02:29.549843 #30935] DEBUG -- : Nat.scrolling:    n/a

D, [2017-11-22T15:02:29.549893 #30935] DEBUG -- : Middle emulation: n/a

D, [2017-11-22T15:02:29.549939 #30935] DEBUG -- : Calibration:      n/a

D, [2017-11-22T15:02:29.550041 #30935] DEBUG -- : Scroll methods:   none

D, [2017-11-22T15:02:29.550143 #30935] DEBUG -- : Click methods:    none

D, [2017-11-22T15:02:29.550242 #30935] DEBUG -- : Disable-w-typing: n/a

D, [2017-11-22T15:02:29.550333 #30935] DEBUG -- : Accel profiles:   n/a

D, [2017-11-22T15:02:29.550404 #30935] DEBUG -- : Rotation:         n/a

D, [2017-11-22T15:02:29.550504 #30935] DEBUG -- : 

D, [2017-11-22T15:02:29.550580 #30935] DEBUG -- : Device:           HDA Intel HDMI HDMI/DP,pcm=8

D, [2017-11-22T15:02:29.550652 #30935] DEBUG -- : Kernel:           /dev/input/event11

D, [2017-11-22T15:02:29.550737 #30935] DEBUG -- : Group:            5

D, [2017-11-22T15:02:29.550810 #30935] DEBUG -- : Seat:             seat0, default

D, [2017-11-22T15:02:29.550916 #30935] DEBUG -- : Capabilities:     

D, [2017-11-22T15:02:29.550987 #30935] DEBUG -- : Tap-to-click:     n/a

D, [2017-11-22T15:02:29.551057 #30935] DEBUG -- : Tap-and-drag:     n/a

D, [2017-11-22T15:02:29.551128 #30935] DEBUG -- : Tap drag lock:    n/a

D, [2017-11-22T15:02:29.551200 #30935] DEBUG -- : Left-handed:      n/a

D, [2017-11-22T15:02:29.551271 #30935] DEBUG -- : Nat.scrolling:    n/a

D, [2017-11-22T15:02:29.551388 #30935] DEBUG -- : Middle emulation: n/a

D, [2017-11-22T15:02:29.551466 #30935] DEBUG -- : Calibration:      n/a

D, [2017-11-22T15:02:29.551539 #30935] DEBUG -- : Scroll methods:   none

D, [2017-11-22T15:02:29.551614 #30935] DEBUG -- : Click methods:    none

D, [2017-11-22T15:02:29.551687 #30935] DEBUG -- : Disable-w-typing: n/a

D, [2017-11-22T15:02:29.551760 #30935] DEBUG -- : Accel profiles:   n/a

D, [2017-11-22T15:02:29.551833 #30935] DEBUG -- : Rotation:         n/a

D, [2017-11-22T15:02:29.551907 #30935] DEBUG -- : 

D, [2017-11-22T15:02:29.552008 #30935] DEBUG -- : Device:           HDA Intel HDMI HDMI/DP,pcm=9

D, [2017-11-22T15:02:29.552086 #30935] DEBUG -- : Kernel:           /dev/input/event12

D, [2017-11-22T15:02:29.552184 #30935] DEBUG -- : Group:            5

D, [2017-11-22T15:02:29.552260 #30935] DEBUG -- : Seat:             seat0, default

D, [2017-11-22T15:02:29.552336 #30935] DEBUG -- : Capabilities:     

D, [2017-11-22T15:02:29.552408 #30935] DEBUG -- : Tap-to-click:     n/a

D, [2017-11-22T15:02:29.552482 #30935] DEBUG -- : Tap-and-drag:     n/a

D, [2017-11-22T15:02:29.552555 #30935] DEBUG -- : Tap drag lock:    n/a

D, [2017-11-22T15:02:29.552652 #30935] DEBUG -- : Left-handed:      n/a

D, [2017-11-22T15:02:29.552725 #30935] DEBUG -- : Nat.scrolling:    n/a

D, [2017-11-22T15:02:29.552807 #30935] DEBUG -- : Middle emulation: n/a

D, [2017-11-22T15:02:29.552883 #30935] DEBUG -- : Calibration:      n/a

D, [2017-11-22T15:02:29.552956 #30935] DEBUG -- : Scroll methods:   none

D, [2017-11-22T15:02:29.553030 #30935] DEBUG -- : Click methods:    none

D, [2017-11-22T15:02:29.553103 #30935] DEBUG -- : Disable-w-typing: n/a

D, [2017-11-22T15:02:29.553203 #30935] DEBUG -- : Accel profiles:   n/a

D, [2017-11-22T15:02:29.553276 #30935] DEBUG -- : Rotation:         n/a

D, [2017-11-22T15:02:29.553358 #30935] DEBUG -- : 

D, [2017-11-22T15:02:29.553435 #30935] DEBUG -- : Device:           HDA Intel HDMI HDMI/DP,pcm=10

D, [2017-11-22T15:02:29.553508 #30935] DEBUG -- : Kernel:           /dev/input/event13

D, [2017-11-22T15:02:29.553596 #30935] DEBUG -- : Group:            5

D, [2017-11-22T15:02:29.553673 #30935] DEBUG -- : Seat:             seat0, default

D, [2017-11-22T15:02:29.553781 #30935] DEBUG -- : Capabilities:     

D, [2017-11-22T15:02:29.553855 #30935] DEBUG -- : Tap-to-click:     n/a

D, [2017-11-22T15:02:29.553928 #30935] DEBUG -- : Tap-and-drag:     n/a

D, [2017-11-22T15:02:29.554001 #30935] DEBUG -- : Tap drag lock:    n/a

D, [2017-11-22T15:02:29.554073 #30935] DEBUG -- : Left-handed:      n/a

D, [2017-11-22T15:02:29.554169 #30935] DEBUG -- : Nat.scrolling:    n/a

D, [2017-11-22T15:02:29.554250 #30935] DEBUG -- : Middle emulation: n/a

D, [2017-11-22T15:02:29.554327 #30935] DEBUG -- : Calibration:      n/a

D, [2017-11-22T15:02:29.554401 #30935] DEBUG -- : Scroll methods:   none

D, [2017-11-22T15:02:29.554475 #30935] DEBUG -- : Click methods:    none

D, [2017-11-22T15:02:29.554549 #30935] DEBUG -- : Disable-w-typing: n/a

D, [2017-11-22T15:02:29.554645 #30935] DEBUG -- : Accel profiles:   n/a

D, [2017-11-22T15:02:29.554731 #30935] DEBUG -- : Rotation:         n/a

D, [2017-11-22T15:02:29.554805 #30935] DEBUG -- : 

D, [2017-11-22T15:02:29.554964 #30935] DEBUG -- : Device:           Lenovo EasyCamera: Lenovo EasyC

D, [2017-11-22T15:02:29.555040 #30935] DEBUG -- : Kernel:           /dev/input/event14

D, [2017-11-22T15:02:29.555129 #30935] DEBUG -- : Group:            6

D, [2017-11-22T15:02:29.555206 #30935] DEBUG -- : Seat:             seat0, default

D, [2017-11-22T15:02:29.555281 #30935] DEBUG -- : Capabilities:     keyboard 

D, [2017-11-22T15:02:29.555356 #30935] DEBUG -- : Tap-to-click:     n/a

D, [2017-11-22T15:02:29.555524 #30935] DEBUG -- : Tap-and-drag:     n/a

D, [2017-11-22T15:02:29.555601 #30935] DEBUG -- : Tap drag lock:    n/a

D, [2017-11-22T15:02:29.555672 #30935] DEBUG -- : Left-handed:      n/a

D, [2017-11-22T15:02:29.555742 #30935] DEBUG -- : Nat.scrolling:    n/a

D, [2017-11-22T15:02:29.555823 #30935] DEBUG -- : Middle emulation: n/a

D, [2017-11-22T15:02:29.555898 #30935] DEBUG -- : Calibration:      n/a

D, [2017-11-22T15:02:29.555972 #30935] DEBUG -- : Scroll methods:   none

D, [2017-11-22T15:02:29.556083 #30935] DEBUG -- : Click methods:    none

D, [2017-11-22T15:02:29.556181 #30935] DEBUG -- : Disable-w-typing: n/a

D, [2017-11-22T15:02:29.556258 #30935] DEBUG -- : Accel profiles:   n/a

D, [2017-11-22T15:02:29.556331 #30935] DEBUG -- : Rotation:         n/a

D, [2017-11-22T15:02:29.556406 #30935] DEBUG -- : 

D, [2017-11-22T15:02:29.556481 #30935] DEBUG -- : Device:           HDA Intel PCH Mic

D, [2017-11-22T15:02:29.556554 #30935] DEBUG -- : Kernel:           /dev/input/event7

D, [2017-11-22T15:02:29.556641 #30935] DEBUG -- : Group:            5

D, [2017-11-22T15:02:29.556720 #30935] DEBUG -- : Seat:             seat0, default

D, [2017-11-22T15:02:29.556794 #30935] DEBUG -- : Capabilities:     

D, [2017-11-22T15:02:29.556868 #30935] DEBUG -- : Tap-to-click:     n/a

D, [2017-11-22T15:02:29.556940 #30935] DEBUG -- : Tap-and-drag:     n/a

D, [2017-11-22T15:02:29.557012 #30935] DEBUG -- : Tap drag lock:    n/a

D, [2017-11-22T15:02:29.557085 #30935] DEBUG -- : Left-handed:      n/a

D, [2017-11-22T15:02:29.557154 #30935] DEBUG -- : Nat.scrolling:    n/a

D, [2017-11-22T15:02:29.557233 #30935] DEBUG -- : Middle emulation: n/a

D, [2017-11-22T15:02:29.557308 #30935] DEBUG -- : Calibration:      n/a

D, [2017-11-22T15:02:29.557382 #30935] DEBUG -- : Scroll methods:   none

D, [2017-11-22T15:02:29.557455 #30935] DEBUG -- : Click methods:    none

D, [2017-11-22T15:02:29.557527 #30935] DEBUG -- : Disable-w-typing: n/a

D, [2017-11-22T15:02:29.557754 #30935] DEBUG -- : Accel profiles:   n/a

D, [2017-11-22T15:02:29.557839 #30935] DEBUG -- : Rotation:         n/a

D, [2017-11-22T15:02:29.557923 #30935] DEBUG -- : 

D, [2017-11-22T15:02:29.558005 #30935] DEBUG -- : Device:           HDA Intel PCH Headphone

D, [2017-11-22T15:02:29.558086 #30935] DEBUG -- : Kernel:           /dev/input/event8

D, [2017-11-22T15:02:29.558179 #30935] DEBUG -- : Group:            5

D, [2017-11-22T15:02:29.558259 #30935] DEBUG -- : Seat:             seat0, default

D, [2017-11-22T15:02:29.558340 #30935] DEBUG -- : Capabilities:     

D, [2017-11-22T15:02:29.558422 #30935] DEBUG -- : Tap-to-click:     n/a

D, [2017-11-22T15:02:29.558504 #30935] DEBUG -- : Tap-and-drag:     n/a

D, [2017-11-22T15:02:29.558581 #30935] DEBUG -- : Tap drag lock:    n/a

D, [2017-11-22T15:02:29.558657 #30935] DEBUG -- : Left-handed:      n/a

D, [2017-11-22T15:02:29.558730 #30935] DEBUG -- : Nat.scrolling:    n/a

D, [2017-11-22T15:02:29.558817 #30935] DEBUG -- : Middle emulation: n/a

D, [2017-11-22T15:02:29.558918 #30935] DEBUG -- : Calibration:      n/a

D, [2017-11-22T15:02:29.558952 #30935] DEBUG -- : Scroll methods:   none

D, [2017-11-22T15:02:29.558986 #30935] DEBUG -- : Click methods:    none

D, [2017-11-22T15:02:29.559018 #30935] DEBUG -- : Disable-w-typing: n/a

D, [2017-11-22T15:02:29.559051 #30935] DEBUG -- : Accel profiles:   n/a

D, [2017-11-22T15:02:29.559082 #30935] DEBUG -- : Rotation:         n/a

D, [2017-11-22T15:02:29.559113 #30935] DEBUG -- : 

D, [2017-11-22T15:02:29.559146 #30935] DEBUG -- : Device:           Ideapad extra buttons

D, [2017-11-22T15:02:29.559178 #30935] DEBUG -- : Kernel:           /dev/input/event6

D, [2017-11-22T15:02:29.559218 #30935] DEBUG -- : Group:            7

D, [2017-11-22T15:02:29.559252 #30935] DEBUG -- : Seat:             seat0, default

D, [2017-11-22T15:02:29.559283 #30935] DEBUG -- : Capabilities:     keyboard 

D, [2017-11-22T15:02:29.559380 #30935] DEBUG -- : Tap-to-click:     n/a

D, [2017-11-22T15:02:29.559410 #30935] DEBUG -- : Tap-and-drag:     n/a

D, [2017-11-22T15:02:29.559438 #30935] DEBUG -- : Tap drag lock:    n/a

D, [2017-11-22T15:02:29.559465 #30935] DEBUG -- : Left-handed:      n/a

D, [2017-11-22T15:02:29.559491 #30935] DEBUG -- : Nat.scrolling:    n/a

D, [2017-11-22T15:02:29.559521 #30935] DEBUG -- : Middle emulation: n/a

D, [2017-11-22T15:02:29.559565 #30935] DEBUG -- : Calibration:      n/a

D, [2017-11-22T15:02:29.559604 #30935] DEBUG -- : Scroll methods:   none

D, [2017-11-22T15:02:29.559642 #30935] DEBUG -- : Click methods:    none

D, [2017-11-22T15:02:29.559680 #30935] DEBUG -- : Disable-w-typing: n/a

D, [2017-11-22T15:02:29.559714 #30935] DEBUG -- : Accel profiles:   n/a

D, [2017-11-22T15:02:29.559748 #30935] DEBUG -- : Rotation:         n/a

D, [2017-11-22T15:02:29.559786 #30935] DEBUG -- : 

D, [2017-11-22T15:02:29.559826 #30935] DEBUG -- : Device:           AT Translated Set 2 keyboard

D, [2017-11-22T15:02:29.559855 #30935] DEBUG -- : Kernel:           /dev/input/event3

D, [2017-11-22T15:02:29.559884 #30935] DEBUG -- : Group:            8

D, [2017-11-22T15:02:29.559903 #30935] DEBUG -- : Seat:             seat0, default

D, [2017-11-22T15:02:29.559922 #30935] DEBUG -- : Capabilities:     keyboard 

D, [2017-11-22T15:02:29.559940 #30935] DEBUG -- : Tap-to-click:     n/a

D, [2017-11-22T15:02:29.559957 #30935] DEBUG -- : Tap-and-drag:     n/a

D, [2017-11-22T15:02:29.559975 #30935] DEBUG -- : Tap drag lock:    n/a

D, [2017-11-22T15:02:29.559992 #30935] DEBUG -- : Left-handed:      n/a

D, [2017-11-22T15:02:29.560010 #30935] DEBUG -- : Nat.scrolling:    n/a

D, [2017-11-22T15:02:29.560033 #30935] DEBUG -- : Middle emulation: n/a

D, [2017-11-22T15:02:29.560051 #30935] DEBUG -- : Calibration:      n/a

D, [2017-11-22T15:02:29.560283 #30935] DEBUG -- : Scroll methods:   none

D, [2017-11-22T15:02:29.560307 #30935] DEBUG -- : Click methods:    none

D, [2017-11-22T15:02:29.560324 #30935] DEBUG -- : Disable-w-typing: n/a

D, [2017-11-22T15:02:29.560340 #30935] DEBUG -- : Accel profiles:   n/a

D, [2017-11-22T15:02:29.560356 #30935] DEBUG -- : Rotation:         n/a

D, [2017-11-22T15:02:29.560371 #30935] DEBUG -- : 

D, [2017-11-22T15:02:29.560387 #30935] DEBUG -- : Device:           ETPS/2 Elantech Touchpad

D, [2017-11-22T15:02:29.560403 #30935] DEBUG -- : Kernel:           /dev/input/event5

D, [2017-11-22T15:02:29.560424 #30935] DEBUG -- : Group:            9

D, [2017-11-22T15:02:29.560440 #30935] DEBUG -- : Seat:             seat0, default

D, [2017-11-22T15:02:29.560456 #30935] DEBUG -- : Size:             96x47mm

D, [2017-11-22T15:02:29.560472 #30935] DEBUG -- : Capabilities:     pointer 

D, [2017-11-22T15:02:29.560488 #30935] DEBUG -- : Tap-to-click:     disabled

D, [2017-11-22T15:02:29.560504 #30935] DEBUG -- : Tap-and-drag:     enabled

D, [2017-11-22T15:02:29.560520 #30935] DEBUG -- : Tap drag lock:    disabled

D, [2017-11-22T15:02:29.560536 #30935] DEBUG -- : Left-handed:      disabled

D, [2017-11-22T15:02:29.560553 #30935] DEBUG -- : Nat.scrolling:    disabled

D, [2017-11-22T15:02:29.560571 #30935] DEBUG -- : Middle emulation: n/a

D, [2017-11-22T15:02:29.560587 #30935] DEBUG -- : Calibration:      n/a

D, [2017-11-22T15:02:29.560603 #30935] DEBUG -- : Scroll methods:   *two-finger edge 

D, [2017-11-22T15:02:29.560619 #30935] DEBUG -- : Click methods:    none

D, [2017-11-22T15:02:29.560635 #30935] DEBUG -- : Disable-w-typing: enabled

D, [2017-11-22T15:02:29.560650 #30935] DEBUG -- : Accel profiles:   none

D, [2017-11-22T15:02:29.560666 #30935] DEBUG -- : Rotation:         n/a

D, [2017-11-22T15:02:29.560683 #30935] DEBUG -- : 

D, [2017-11-22T15:02:29.560755 #30935] DEBUG -- : {:libinput_command=>"stdbuf -oL -- libinput-debug-events --enable-dwt --device /dev/input/event5"}

/var/lib/gems/2.3.0/gems/fusuma-0.3.3/lib/fusuma.rb:37:in `each': Interrupt
	from /var/lib/gems/2.3.0/gems/fusuma-0.3.3/lib/fusuma.rb:37:in `block in read_libinput'
	from /usr/lib/ruby/2.3.0/open3.rb:205:in `popen_run'
	from /usr/lib/ruby/2.3.0/open3.rb:95:in `popen3'
	from /var/lib/gems/2.3.0/gems/fusuma-0.3.3/lib/fusuma.rb:36:in `read_libinput'
	from /var/lib/gems/2.3.0/gems/fusuma-0.3.3/lib/fusuma.rb:21:in `run'
	from /var/lib/gems/2.3.0/gems/fusuma-0.3.3/exe/fusuma:21:in `<top (required)>'
	from /usr/local/bin/fusuma:22:in `load'
	from /usr/local/bin/fusuma:22:in `<main>'
Does anyone know how to solve it?
