### ISSUE TITLE
can anyone tell me how to configure the button PageUp or PageDown

### ISSUE THREAD

**Issue by Hainguyen1210** [iberianpig/fusuma#6]

**Comment by iberianpig** [comment]
You should check the script.

`https://cgit.freedesktop.org/xorg/proto/x11proto/plain/keysymdef.h`

```
#define XK_Page_Up                       0xff55
#define XK_Page_Down                     0xff56
```

It would work with `Page_Up` and `Page_Down`.

**Comment by Hainguyen1210** [comment]
Oh, thank you, I just did not know where to look for it
