### ISSUE TITLE
Not recognizing 3 or 4 finger gestures on elementary OS 0.4.1

### ISSUE THREAD

**Issue by Fabi0Z** [iberianpig/fusuma#61]
I'm running fusuma on elementary OS 0.4.1 but it seem to not recognize more than two fingers in the touchpad

when i run `libinput-debug-events` if i try to use 3 or 4 fingers in the touchpad it doesn't return nothing, I'm using a synaptic touchpad and support both 3 and 4 fingers (I had used it in Windows and checked with `xinput --list-props <my touchpad id>`). I'm not sure that this can be marked as a fusuma issue, seems more to be a libinput issue, so don't worry about eventually closing it, but some help to solve my problem will be appreciated!

**Comment by sourbloom** [comment]
I'm really not that familiar with this sort of stuff, but I've played around with mice input before under X. You can try switching the driver out by modifying your xorg configuration.

Take a look at this: https://unix.stackexchange.com/a/131447

The part you want to play with looks like this:
```
Section "InputClass"
        Identifier "touchpad catchall"
        Driver "synaptics"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
EndSection
```

The `Driver` property can be changed to different values, like `mouse`. You'll have to look online for a better list that might match your device.

Sorry this isn't more helpful, hopefully someone else can chime in with better info :)
