### ISSUE TITLE
Keyevent not executed

### ISSUE THREAD

**Issue by Slowerzs** [iberianpig/fusuma#65]
I have configured my config.yml to execute ctrl+v, ctrl+c, alt+Tab, alt+Shift+Tab with 3-fingers swipe.
Swipes are properly detected when I run fusuma, but keyevents are not executed : see below
 ```
$ fusuma
I, [2018-02-18T12:59:24.902704 #4106]  INFO -- : trigger keyevent: ctrl+v
I, [2018-02-18T12:59:25.061422 #4106]  INFO -- : trigger keyevent: alt+Tab
I, [2018-02-18T12:59:25.216623 #4106]  INFO -- : trigger keyevent: ctrl+c
I, [2018-02-18T12:59:25.490811 #4106]  INFO -- : trigger keyevent: alt+Shift+Tab
I, [2018-02-18T12:59:25.651239 #4106]  INFO -- : trigger keyevent: ctrl+c
I, [2018-02-18T12:59:25.991581 #4106]  INFO -- : trigger keyevent: alt+Shift+Tab
```
But nothing is copied, pasted, and it doesn't switch between windows. I'm only interested in the App switcher with 3-fingers swipe actually.

**Comment by rmasclef** [comment]
Got the same issue with 3 fingers up or down which is triggers `super + a`/`super + s`.

But, sometimes, after a restart (but not at every restarts), the events are triggered.

@Slowerzs silly question but, did you had `fusuma` command at startup ? if not, the events will never be triggered :+1:
