### ISSUE TITLE
Ubuntu 18.04 ships with ruby 2.5, needs manual ruby 2.3 installation

### ISSUE THREAD

**Issue by faiv** [iberianpig/fusuma#66]
After upgrading to the latest 18.04 development version, and upgrading to ruby 2.5, fusuma did not work anymore. I had to manually install ruby 2.3 to run fusuma again. A symlink did not help.

ln -s /usr/bin/ruby2.3 /usr/bin/ruby
Traceback (most recent call last):
	2: from /usr/local/bin/fusuma:22:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems.rb:263:in `bin_path'
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem fusuma (>= 0.a) with executable fusuma (Gem::GemNotFoundException)

**Comment by olegsenko** [comment]
I have ASUS n750 laptop with ruby 2.5 installed. 
For me libinput 1.8 is working, and the latest one didn't recognize any gestures in fusuma.

**Comment by iberianpig** [comment]
@faiv Why did you need to downgrade Ruby to 2.5?
Fusuma works with Ruby 2.5 on my environment.

**Comment by pockata-kt** [comment]
I'm having the same issue, ruby version `ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]`
