### ISSUE TITLE
security issues

### ISSUE THREAD

**Issue by the0demiurge** [iberianpig/fusuma#71]
By adding user to "input" group, one's all input behavior are easy be monitored, which       may cause leak of password or so.

Users should be warned

**Comment by iberianpig** [comment]
@the0demiurge Thanks!
Do you have any option that keep it secure from the leak?

I think below is ok
* run fusuma with `sudo fusuma` without adding user to "input" group.

**Comment by whot** [comment]
You can drop a sudo config snippet to allow running fusuma without a password as sudo. IMO that's the easiest solution.

**Comment by iberianpig** [comment]
@whot Do you mean that it is better to execute fusuma without sudo with configuring `sudoers` file?

**Comment by whot** [comment]
you can configure sudo so you can execute specific commands without asking for passwords. You still need to run it as `sudo <command>` though

**Comment by js-d-coder** [comment]
`sudo fusuma` does not works. I have config file in both `~/.config/fusuma` and `/root/.config/fusuma/`.
