### ISSUE TITLE
feature request: edge sweep

### ISSUE THREAD

**Issue by mscalone** [iberianpig/fusuma#74]
Great project! 

I wonder how complicated is to add the "sweep from edge" gesture (maybe with 1 or two fingers) it would be great to bind it to alt+tab (and alt+shift+tab) action by default.

thanks

**Comment by linweilian03** [comment]
[https://github.com/iberianpig/fusuma/issues/27](url)
I proposed the similar issue before, and got no reply.

**Comment by iberianpig** [comment]
Edge swipe is require fingers' positions on the touchpad.

`synclient` used in xSwipe prints fingers' positions on the touch pad.
But `libinput-debug-events` doesn't print it. 

For I make edge swipe function, I need to know how to get the information.
