### ISSUE TITLE
Questionable necessity of --enable-dwt

### ISSUE THREAD

**Issue by z0rc** [iberianpig/fusuma#78]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Read Documents. https://github.com/iberianpig/fusuma#installation
    * Checked that `libinput-debug-events` worked correctly.
    * Reproduced the problem in latest version. Update fusuma with `gem update fusuma`
    * Checked that your issue isn't already filed: https://github.com/iberianpig/fusuma/issues

### Description

`libinput-debug-events` launched with `--enable-dwt` option and this is hardcoded. It's usually a desired option to turn it on, but at fusuma case it's meaningless. This option affects whole libinput, which should be managed by user via GNOME/KDE/whatever input configuration. Forcefully enabling it for fusuma isn't right and may lead to hard to debug issue when user decides to disable this option for various reasons.

As this option doesn't change `libinput-debug-events` output, I believe it should be dropped from fusuma.

### Versions

fusuma: b1ab717
OS: Kubuntu 17.10
libinput: 1.8.4

**Comment by iberianpig** [comment]
Oh, thanks! Could you make pull request?

**Comment by z0rc** [comment]
Sure, see linked PR.
