### ISSUE TITLE
Error: /usr/share/ruby/open3.rb:199:in `spawn': No such file or directory - libinput-list-devices (Errno::ENOENT)

### ISSUE THREAD

**Issue by zoppagency** [iberianpig/fusuma#84]
When start fusuma report this error. 

/usr/share/ruby/open3.rb:199:in `spawn': No such file or directory - libinput-list-devices (Errno::ENOENT)

my fusuma version is 0.71
Fedora 28
4.16.3 kernel

**Comment by iberianpig** [comment]
You need libinput release 1.0 or later. Install libinput-tools:

$ sudo apt-get install libinput-tools

**Comment by iberianpig** [comment]
@zoppagency fix with https://github.com/iberianpig/fusuma/commit/c399e7a710b1efed5b9a7db66582c91fa5f626e1 .
Could you please check with new version(install with `gem update fusuma`)?

**Comment by MisterPresident** [comment]
Thank you, for me it's working again!
