### ISSUE TITLE
Unable to run Fusuma on Arch: command not found

### ISSUE THREAD

**Issue by navtojchahal** [iberianpig/fusuma#96]
I installed fusuma (0.10.2) however am not able to run it. I couldn't find any solutions through "googling". What should I do?

My Setup: Acer Laptop - Arch - Gnome - Xorg

![fusuma not working](https://user-images.githubusercontent.com/37762455/44884642-4729be00-ac71-11e8-9f39-ac254e792f91.png)

**Comment by iberianpig** [comment]
Could you try `fusuma -v` and paste output here?

**Comment by navtojchahal** [comment]
![fusuma -v](https://user-images.githubusercontent.com/37762455/44888447-1607b880-ac86-11e8-8642-67028397438a.png)

I got the "fusuma" command working in terminal once today by messing around with the $PATH commands. But it went back to "command not found" when I reopened the terminal.

**Comment by navtojchahal** [comment]
This is how I got it working temporarily..
![temporary fix](https://user-images.githubusercontent.com/37762455/44888680-48fe7c00-ac87-11e8-8e75-4266b8e94d75.png)

**Comment by iberianpig** [comment]
It seems that Gem installation path can not be read.
Please confirm your Ruby environment.

**Comment by navtojchahal** [comment]
![gem environment](https://user-images.githubusercontent.com/37762455/44889980-20798080-ac8d-11e8-8829-0d036d57b4ab.png)

**Comment by iberianpig** [comment]
You may read (https://wiki.archlinux.org/index.php/Ruby) and try set up again.
Then reload your ~/.bashrc.

**Comment by navtojchahal** [comment]
Okay thanks, I got it working.

I added >> PATH="$PATH:$(ruby -e 'print Gem.user_dir')/bin" << to "/etc/bash.bashrc" using nano in terminal and rebooted. It's been working great since then.
